---
# yaml-language-server: $schema=https://schemas.vwn.app/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # To override the default UID/GID for pgAdmin, uncomment and set these values:
        # PGADMIN_UID: "1000" # Custom UID value
        # PGADMIN_GID: "1000" # Custom GID value

        PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_DEFAULT_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_DEFAULT_PASSWORD }}"

        pgpass: |
          ${DB_SERVER}:5432:*:{{ .POSTGRES_SUPER_USER }}:{{ .POSTGRES_SUPER_PASS }}

        PGADMIN_CONFIG_MAIL_SERVER: "'{{ .SMTP_SERVER }}'"
        PGADMIN_CONFIG_MAIL_USERNAME: "'{{ .SMTP_USERNAME }}'"
        PGADMIN_CONFIG_MAIL_PASSWORD: "'{{ .SMTP_PASSWORD }}'"
        PGADMIN_CONFIG_SECURITY_EMAIL_SENDER: "'pgAdmin <{{ .SMTP_MAIL_FROM }}>'"
        PGADMIN_CONFIG_MAIL_PORT: "587"
        PGADMIN_CONFIG_MAIL_USE_TLS: "True"
        PGADMIN_CONFIG_MAIL_DEBUG: "True"
        PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "True"

  dataFrom:
    - extract:
        key: pgadmin
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp
