---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # To override the default UID/GID for pgAdmin, uncomment and set these values:
        # PGADMIN_UID: "1000" # Custom UID value
        # PGADMIN_GID: "1000" # Custom GID value

        PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_DEFAULT_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_DEFAULT_PASSWORD }}"
        pgpass: |
          ${DB_SERVER}:5432:*:{{ .POSTGRES_SUPER_USER }}:{{ .POSTGRES_SUPER_PASS }}
  dataFrom:
    - extract:
        key: pgadmin
    - extract:
        key: cloudnative-pg
