---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        # To override the default UID/GID for pgAdmin, uncomment and set these values:
        # PGADMIN_UID: "1000" # Custom UID value
        # PGADMIN_GID: "1000" # Custom GID value

        PGADMIN_DEFAULT_EMAIL: "{{ .PA_PGADMIN_DEFAULT_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PA_PGADMIN_DEFAULT_PASSWORD }}"

        pgpass: |
          ${DB_SERVER}:5432:*:{{ .DB_POSTGRES_SUPER_USER }}:{{ .DB_POSTGRES_SUPER_PASS }}

        PGADMIN_CONFIG_MAIL_SERVER: "'{{ .EM_SMTP_SERVER }}'"
        PGADMIN_CONFIG_MAIL_USERNAME: "'{{ .EM_SMTP_USERNAME }}'"
        PGADMIN_CONFIG_MAIL_PASSWORD: "'{{ .EM_SMTP_PASSWORD }}'"
        PGADMIN_CONFIG_SECURITY_EMAIL_SENDER: "'pgAdmin <{{ .EM_SMTP_MAIL_FROM }}>'"
        PGADMIN_CONFIG_MAIL_PORT: "587"
        PGADMIN_CONFIG_MAIL_USE_TLS: "True"

        PGADMIN_CONFIG_OAUTH2_CONFIG: |
          [
            {
              'OAUTH2_NAME':'Van Wetten ID',
              'OAUTH2_DISPLAY_NAME':'Van Wetten ID',
              'OAUTH2_CLIENT_ID':'{{ .PA_OIDC_CLIENT_ID }}',
              'OAUTH2_CLIENT_SECRET':'{{ .PA_OIDC_CLIENT_SECRET }}',
              'OAUTH2_TOKEN_URL':'{{ .PA_OIDC_BASE_URL }}/application/o/token/',
              'OAUTH2_AUTHORIZATION_URL':'{{ .PA_OIDC_BASE_URL }}/application/o/authorize/',
              'OAUTH2_API_BASE_URL':'{{ .PA_OIDC_BASE_URL }}/',
              'OAUTH2_USERINFO_ENDPOINT':'{{ .PA_OIDC_BASE_URL }}/application/o/userinfo/',
              'OAUTH2_SERVER_METADATA_URL':'{{ .PA_OIDC_BASE_URL }}/application/o/pgadmin/.well-known/openid-configuration',
              'OAUTH2_USERNAME_CLAIM': 'email',
              'OAUTH2_SCOPE':'openid email profile',
              'OAUTH2_ADDITIONAL_CLAIMS': {
                  'groups': ["Administrators"]
              },
              'OAUTH2_ICON':'fa-openid',
              'OAUTH2_BUTTON_COLOR':'#429DE2'
            }
          ]

        servers.json: |
          {
            "Servers": {
              "1": {
                "Name": "home-ops",
                "Group": "Shared",
                "Host": "${DB_SERVER}",
                "Port": 5432,
                "MaintenanceDB": "postgres",
                "Username": "{{ .DB_POSTGRES_SUPER_USER }}",
                "Shared": true,
                "SharedUsername": "{{ .DB_POSTGRES_SUPER_USER }}",
                "ConnectionParameters": {
                    "sslmode": "prefer",
                    "connect_timeout": 10,
                    "passfile": "/.pgpass"
                },
                "Tags": [
                  {
                    "color": "#234D6E",
                    "text": "Cluster"
                  }
                ],
                "PostConnectionSQL": "set timezone='${TIMEZONE}'"
              }
            }
          }
  dataFrom:
    - extract:
        key: pgadmin
      rewrite: [{regexp: {source: (.*), target: PA_$1}}]
    - extract:
        key: cloudnative-pg
      rewrite: [{regexp: {source: (.*), target: DB_$1}}]
    - extract:
        key: smtp
      rewrite: [{regexp: {source: (.*), target: EM_$1}}]
