---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    timeout: 2m
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      pgadmin:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/dpage/pgadmin4
              tag: 9.4.0
            env:
              PGADMIN_LISTEN_PORT: &port 80
              PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
              PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
            envFrom:
              - secretRef:
                  name: pgadmin-secret
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
        runAsUser: "${APP_UID:-5050}"
        runAsGroup: "${APP_GID:-5050}"
        fsGroup: "${APP_GID:-5050}"
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
    persistence:
      config:
        existingClaim: pgadmin-config
        advancedMounts:
          pgadmin:
            app:
              - path: /var/lib/pgadmin
      servers-json-file:
        type: configMap
        name: servers.json
        globalMounts:
          - path: /pgadmin4/servers.json
            subPath: servers.json
            readOnly: true
    route:
      app:
        hostnames:
          - "pgadmin.${DOMAIN_APP}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
        rules:
          - backendRefs:
              - identifier: app
                port: *port
