---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &currentCluster postgres-v17
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 30
  storage:
    size: 20Gi

  enableSuperuserAccess: true
  superuserSecret:
    name: &secret cloudnative-pg-secret

  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: "s3://cloudnative-pg"
      endpointURL: "https://gateway.storjshare.io"
      serverName: *currentCluster
      s3Credentials:
        accessKeyId:
          name: *secret
          key: S3_ACCESS_KEY
        secretAccessKey:
          name: *secret
          key: S3_SECRET_KEY

  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: cloudnative-pg-bootstrap-secret

  #   # Recovers from the latest S3 backup
  #   recovery:
  #     source: &previousCluster postgres-v17

  # externalClusters:
  #   - name: *previousCluster
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: postgres-v17
