---
apiVersion: v1
kind: Service
metadata:
  name: &app postgres-v17
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "db.${DOMAIN_APP}"
    lbipam.cilium.io/ips: 10.60.0.99
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: *app
    cnpg.io/instanceRole: primary
