---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: redis-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis
        property: REDIS_PASSWORD
