---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cluster-secrets
spec:
  refreshTime: 5m
  externalSecretName: cluster-secrets
  namespaceSelectors:
    - matchLabels:
        external-secrets.io/cluster-secrets: "true"
  externalSecretSpec:
    refreshPolicy: OnChange
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: cluster-secrets
      creationPolicy: Owner
      deletionPolicy: Delete
      template:
        data:
          # Domains
          DOMAIN_APP: "{{ .CL_DOMAIN_APP }}"
          DOMAIN_CASA: "{{ .CL_DOMAIN_CASA }}"
          DOMAIN_DEV: "{{ .CL_DOMAIN_DEV }}"
          DOMAIN_ID: "{{ .CL_DOMAIN_ID }}"
          DOMAIN_IO: "{{ .CL_DOMAIN_IO }}"
          DOMAIN_PROXII: "{{ .CL_DOMAIN_PROXII }}"
          DOMAIN_TS: "{{ .TS_DOMAIN }}"
          # Servers
          DB_SERVER: "{{ .CL_DB_SERVER }}"
          # MQTT_HOST: "{{ .CL_MQTT_HOST }}"
          NAS_SERVER: "{{ .CL_NAS_SERVER }}"
          NFS_SERVER: "{{ .CL_NFS_SERVER }}"
          SMB_SERVER: "{{ .CL_SMB_SERVER }}"
          REDIS_SERVER: "{{ .CL_REDIS_SERVER }}"
          DRAGONFLY_SERVER: "{{ .CL_DRAGONFLY_SERVER }}"
    dataFrom:
      - extract:
          key: cluster
        rewrite: [{regexp: {source: (.*), target: CL_$1}}]
      - extract:
          key: tailscale
        rewrite: [{regexp: {source: (.*), target: TS_$1}}]
