---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cluster-issuers
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  wait: true
  prune: true
  path: ./kubernetes/apps/cert-manager/cluster-issuers/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: flux-system
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-staging
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-production
