---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app certificates-import
  namespace: &namespace network
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components: []
  wait: false
  prune: true
  interval: 5m
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/network/certificates/import
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cluster-secrets
      namespace: external-secrets
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app certificates-export
  namespace: &namespace network
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components: []
  wait: false
  prune: true
  interval: 5m
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/network/certificates/export
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cluster-secrets
      namespace: external-secrets
    - name: certificates-import
      namespace: *namespace
