---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age14ytjrjdtj7azyqknt0cj854fqcyqlrrrkyck5kyc2ulkug70vswsj2w0k9"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age14ytjrjdtj7azyqknt0cj854fqcyqlrrrkyck5kyc2ulkug70vswsj2w0k9"
stores:
  yaml:
    indent: 2
