---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods verified
            fallthrough in-addr.arpa ip6.arpa
        }
        autopath @kubernetes
        forward . /etc/resolv.conf
        cache {
            prefetch 20
            serve_stale
        }
        loop
        reload
        loadbalance
        prometheus 0.0.0.0:9153
        log {
            class error
        }
    }
    ts.net:53 {
        errors
        cache 30
        forward . ${TAILSCALE_DNS_IP}
    }
