---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale-operator
  namespace: &namespace tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: 1.84.3
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: tailscale-operator
      valuesKey: clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-operator
      valuesKey: clientSecret
      targetPath: oauth.clientSecret
  values:
    fullnameOverride: *app
    operatorConfig:
      hostname: tailscale-operator
      defaultTags:
        - "tag:k8s-operator"

    proxyConfig:
      defaultTags: "tag:k8s"
