---
# yaml-language-server: $schema=https://schemas.clustrs.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_APP/./-}"
spec:
  secretName: "${DOMAIN_APP/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_APP}"
  dnsNames: ["${DOMAIN_APP}", "*.${DOMAIN_APP}"]
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_CASA/./-}"
spec:
  secretName: "${DOMAIN_CASA/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_CASA}"
  dnsNames: ["${DOMAIN_CASA}", "*.${DOMAIN_CASA}"]
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_ID/./-}"
spec:
  secretName: "${DOMAIN_ID/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_ID}"
  dnsNames: ["${DOMAIN_ID}", "*.${DOMAIN_ID}"]
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_DEV/./-}"
spec:
  secretName: "${DOMAIN_DEV/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_DEV}"
  dnsNames: ["${DOMAIN_DEV}", "*.${DOMAIN_DEV}"]
