---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "${DOMAIN_APP/./-}-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "${DOMAIN_APP/./-}-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" }}'
      tls.key: '{{ index . "tls.key" }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "${DOMAIN_APP/./-}-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "${DOMAIN_APP/./-}-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "${DOMAIN_CASA/./-}-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "${DOMAIN_CASA/./-}-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" }}'
      tls.key: '{{ index . "tls.key" }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "${DOMAIN_CASA/./-}-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "${DOMAIN_CASA/./-}-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "${DOMAIN_ID/./-}-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "${DOMAIN_ID/./-}-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" }}'
      tls.key: '{{ index . "tls.key" }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "${DOMAIN_ID/./-}-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "${DOMAIN_ID/./-}-tls"
          property: *key
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "${DOMAIN_DEV/./-}-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "${DOMAIN_DEV/./-}-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" }}'
      tls.key: '{{ index . "tls.key" }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "${DOMAIN_DEV/./-}-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "${DOMAIN_DEV/./-}-tls"
          property: *key
