---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: homepage-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID: "{{ .CF_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID: "{{ .CF_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN: "{{ .CF_API_TOKEN }}"
        HOMEPAGE_VAR_LATITUDE: "{{ .HP_LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .HP_LONGITUDE }}"
        HOMEPAGE_VAR_TRUENAS_API_KEY: "{{ .HP_TRUENAS_API_KEY }}"
        HOMEPAGE_VAR_PAPERLESS_API_KEY: "{{ .PL_API_KEY }}"
        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .IM_HOMEPAGE_API_KEY }}"
        # HOMEPAGE_VAR_KAGI_SESSION_TOKEN: "{{ .HP_KAGI_SESSION_TOKEN }}"
        # HOMEPAGE_VAR_KARAKEEP_API_KEY: "{{ .HP_KARAKEEP_API_KEY }}"
        # HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .HP_BAZARR_API_KEY }}"
        # HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .PR_PROWLARR_API_KEY }}"
        # HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RR_RADARR_API_KEY }}"
        # HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SR_SONARR_API_KEY }}"
        # HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .SB_SABNZBD_API_KEY }}"
        # HOMEPAGE_VAR_JELLYFIN_API_KEY: "{{ .HP_JELLYFIN_API_KEY }}"
        # HOMEPAGE_VAR_KOMGA_API_KEY: "{{ .HP_KOMGA_API_KEY }}"
        # HOMEPAGE_VAR_PLEX_TOKEN: "{{ .PX_PLEX_TOKEN }}"
        # HOMEPAGE_VAR_TAUTULLI_API_KEY: "{{ .HP_TAUTULLI_API_KEY }}"
        # HOMEPAGE_VAR_STASH_API_KEY: "{{ .HP_STASH_API_KEY }}"
  dataFrom:
    - extract:
        key: homepage
      rewrite: [{regexp: {source: (.*), target: HP_$1}}]
    - extract:
        key: cloudflare
      rewrite: [{regexp: {source: (.*), target: CF_$1}}]
    - extract:
        key: paperless
      rewrite: [{regexp: {source: (.*), target: PL_$1}}]
    - extract:
        key: immich
      rewrite: [{regexp: {source: (.*), target: IM_$1}}]

