---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: robusta
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: robusta-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        ACCOUNT_ID: "{{ .RB_ACCOUNT_ID }}"
        SIGNING_KEY: "{{ .RB_SIGNING_KEY }}"
        SINK_TOKEN: "{{ .RB_SINK_TOKEN }}"
  dataFrom:
    - extract:
        key: robusta
      rewrite: [{regexp: {source: (.*), target: RB_$1}}]
