---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app robusta
spec:
  interval: 1h
  chart:
    spec:
      chart: robusta
      version: 0.26.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: robusta
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    clusterName: home-ops
    globalConfig:
      signing_key: "{{ env.SIGNING_KEY }}"
      account_id: "{{ env.ACCOUNT_ID }}"
    sinksConfig:
      - robusta_sink:
          name: robusta_ui_sink
          token: "{{ env.SINK_TOKEN }}"
    enablePrometheusStack: false
    enablePlatformPlaybooks: true
    runner:
      sendAdditionalTelemetry: true
      additional_env_vars:
        - name: ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: &secret robusta-secret
              key: ACCOUNT_ID
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: *secret
              key: SIGNING_KEY
        - name: SINK_TOKEN
          valueFrom:
            secretKeyRef:
              name: *secret
              key: SINK_TOKEN
    enableHolmesGPT: true
    enabledManagedConfiguration: true
    holmes:
      toolsets:
        kubernetes/kube-lineage-extras:
          enabled: true
        kubernetes/kube-prometheus-stack:
          enabled: true
        kubernetes/live-metrics:
          enabled: true
        helm/core:
          enabled: true
        bash:
          enabled: true
          config:
            kubectl:
              allowed_images: []
      additionalEnvVars:
        - name: ROBUSTA_AI
          value: "true"
        - name: ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: *secret
              key: ACCOUNT_ID
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: *secret
              key: SIGNING_KEY
        - name: SINK_TOKEN
          valueFrom:
            secretKeyRef:
              name: *secret
              key: SINK_TOKEN

