---
# yaml-language-server: $schema=https://schemas.clustrs.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: robusta
spec:
  interval: 1h
  url: https://robusta-charts.storage.googleapis.com
  timeout: 5m
