---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app coder
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: coder
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    coder:
      image:
        tag: 2.25.0
      env:
        - name: CODER_ACCESS_URL
          value: "https://${APP}.${DOMAIN_APP}"
    service:
      type: ClusterIP
