---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app coder
spec:
  interval: 1h
  chart:
    spec:
      chart: coder
      version: 2.25.1
      sourceRef:
        kind: HelmRepository
        name: coder
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    coder:
      image:
        tag: v2.25.1
      env:
        - name: CODER_ACCESS_URL
          value: "https://${APP}.${DOMAIN_APP}"
    service:
      type: ClusterIP
