---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: searxng-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        settings.yml: |
          use_default_settings: true
          general:
            instance_name: "SearXNG"
          server:
            port: 8080
            bind_address: 0.0.0.0
            secret_key: "{{ .SEARXNG_SECRET_KEY }}"
          ui:
            static_use_hash: true
        limiter.toml: |
          [botdetection.ip_limit]
          # To get unlimited access in a local network, by default link-local addresses
          # (networks) are not monitored by the ip_limit
          filter_link_local = false

          # activate link_token method in the ip_limit method
          link_token = false

          [botdetection.ip_lists]
          # Block and pass IP lists
          block_ip = []
          pass_ip = []

          # Activate passlist of (hardcoded) IPs from the SearXNG organization
          pass_searxng_org = false
  dataFrom:
    - extract:
        key: searxng
      rewrite: [{regexp: {source: (.*), target: SEARXNG_$1}}]
