---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng
spec:
  defaultBackend:
    service:
      name: searxng
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - search
