---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-relay-gatus-endpoint
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: SMTP Relay
        group: Infrastructure Services
        url: tcp://smtp-relay.network.svc.cluster.local:25
        interval: 1m
        ui:
          hide-hostname: false
          hide-url: false
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: gotify
