---
# yaml-language-server: $schema=https://schemas.clustrs.dev/tailscale.com/connector_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: app-connector
spec:
  appConnector:
    routes:
      - 10.43.0.0/16  # Pod CIDR
      - 10.42.0.0/16  # Service CIDR (if different)
  hostname: homelab-ingress
