---
# yaml-language-server: $schema=https://schemas.clustrs.dev/tailscale.com/connector_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: exit-node
spec:
  exitNode: true
  hostname: homelab-egress
