---
apiVersion: v1
kind: Service
metadata:
  name: tailscale-dns-static
  namespace: tailscale
spec:
  type: ClusterIP
  clusterIP: "10.43.0.53"  # Static IP for CoreDNS to use
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 1053
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 1053
  selector:
    app: nameserver
