---
# yaml-language-server: $schema=https://schemas.clustrs.dev/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: tailnet-egress
  namespace: tailscale
spec:
  type: egress
  replicas: 2  # High availability with 2 proxy pods
