---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: n8n-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        # Database Init
        INIT_POSTGRES_HOST: "${DB_SERVER}"
        INIT_POSTGRES_DBNAME: "{{ .NN_POSTGRES_DB }}"
        INIT_POSTGRES_USER: "{{ .NN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .NN_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .DB_POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .DB_POSTGRES_SUPER_PASS }}"
        # App Configuration
        DB_POSTGRESDB_DATABASE: "{{ .NN_POSTGRES_DB }}"
        DB_POSTGRESDB_PASSWORD: "{{ .NN_POSTGRES_PASSWORD }}"
        DB_POSTGRESDB_USER: "{{ .NN_POSTGRES_USER }}"
        N8N_ENCRYPTION_KEY: "{{ .NN_ENCRYPTION_KEY }}"
        N8N_LICENSE_ACTIVATION_KEY: "{{ .NN_LICENSE_ACTIVATION_KEY }}"
        N8N_SMTP_HOST: "{{ .SMTP_SERVER }}"
        N8N_SMTP_PASS: "{{ .SMTP_PASSWORD }}"
        N8N_SMTP_SENDER: "n8n <{{ .SMTP_MAIL_FROM }}>"
        N8N_SMTP_USER: "{{ .SMTP_USERNAME }}"
  dataFrom:
    - extract:
        key: n8n
      rewrite: [{regexp: {source: (.*), target: NN_$1}}]
    - extract:
        key: cloudnative-pg
      rewrite: [{regexp: {source: (.*), target: DB_$1}}]
    - extract:
        key: smtp
      rewrite: [{regexp: {source: (.*), target: SMTP_$1}}]
