---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-operator
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  dataFrom:
    - extract:
        key: cloudnative-pg
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        # S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        # S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-bootstrap
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  dataFrom:
    - extract:
        key: cloudnative-pg
  target:
    name: cloudnative-pg-bootstrap-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: "{{ .POSTGRES_BOOTSTRAP_USER }}"
        password: "{{ .POSTGRES_BOOTSTRAP_PASS }}"
