---
# yaml-language-server: $schema=https://schemas.vwn.app/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudnative-pg
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: -1
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    crds:
      create: true
    replicaCount: 1
    serviceAccount:
      create: true
    monitoring:
      enabled: true
      prometheusRule:
        enabled: true
      podMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi

