---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tunnel-secret
    template:
      engineVersion: v2
      data:
        TUNNEL_TOKEN: "{{ .CF_TUNNEL_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflared
      rewrite:
        - regexp:
            source: (.*)
            target: CF_$1
