# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nSYO9/Z9m6ytDdqWkuJlLS/YBikKpGHbb7yHz/dzYwhJYv/c6K56HQ==,iv:6TUz18W2JfXuDjGsYVdgRVON8VWKqOwcJ5Kx7y6H0aI=,tag:kKy8aTsJvKWBV59Phvs3kg==,type:str]
sops:
  age:
    - recipient: age1kk5hqm27rv9l4engrl8xvudqnzlsrs698z22lmy5409v0ha66pjq02rhuq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN1h1dVBLdkt0T0tWbi9y
        UTcrbHR4U2I0VlorNUkySkU5UXUyclB2MjNjCllheEdpaXJhNnpaT0habDNUNlNi
        Tm82UTJuYmFjM1lSVW1rdDh2NTN3NDgKLS0tIElMUW54eTFpUE5JTkdJS1M2d29J
        dlRkd0E2YVB4dG5rYXBiV0ZzOWo2S3MKfMzkAQoTvw4+h3CaPvQyJt7ibXH4FEu4
        qk68DHsBE+UIGhF5ddxIhz+xA8tZqBuNB+E8PmIDOLYhU4cGX6ZW6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T13:35:56Z"
  mac: ENC[AES256_GCM,data:cU0IEJsZpBvTD/G5DR4xtAZQ5XQYFXtlTvhccvq2W8nY2gbwmHvWGu4zHLgQK9ny1GUuau1gDz0Ylc5jbg/HclXFVQpfgT/bP6uVItJUCoQD+Gml3MR7kQ4fSsLwiTdRIlxn91j4EQtqd9HIYQQsVGS3nnuRSvPRJ5VThoEtGWc=,iv:W8V0TM5ol2fSD1K3NyXxvya8HknryH4sCppSGfZ2i+g=,tag:d/7AAALZLUA6uTYfML6FCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
