# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:2w51I1CCIiGDVpjrDUbUQ9YXYQ4VtMlqVRQy1ogrqnnph4syIwshlA==,iv:AG98wPY1KB/L7uP+NXR5eC4V9tjTP7kVHvDHKRAtOeU=,tag:4yy5CN6x41IbG1iFbJinFQ==,type:str]
sops:
  age:
    - recipient: age17dwj6gpcv9evtrhwa8e0xcast9j2z50qha5rwl7c9jldynxwkqgqmmkxf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYmVEcVB6YzUxNHV1M0Y5
        ZmdlamduK290SlZZZzlXOEJucGp4clYwYWg4Ck1MSWxzWDhhT21ZT3g0dnI5bmlO
        dGZTL2E5d3l2TjFrTU5KVnNyK2pnQVkKLS0tIEZ6dEFZVm5xRUpMcmZmNWQ4d3JY
        ZUg4dDhMWUFlZUc4TTB0YVQ4WkVodWcKuloyLZctDGh1q6hrFB3ktYcPYSd9O5Yl
        vwrDEzNZs8JLvip6GZUR5g5+0rfZG0g+mz2nwkSB20LfnRnJyGg45Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-12T20:38:19Z"
  mac: ENC[AES256_GCM,data:xJ751FjInT/g5D1jh01HYSXOYzCFkJDJZhsI42EaA+qdRefmXoJhe7M+tenEAOGrXaRtWK7HMwAzc7iy/c1+9dtIw36F63xYPr1PZmNhDR8cgR/3gBWlOb4EsoFoBX4o06xv4ZeaSdCCn3erUUwgYOGBTkHolK6MgvEGauyPSfU=,iv:5A+8q9gebudPoNdJ8SGTgqVS06dXpB1bGpAWDETyilI=,tag:VOEdrr4WmEHp6uVvIsibjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
