# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sX+X6m/vFg+B9r8KAjMXJueoiP7zLzeRsSpWs+cat2rS446z+ghAdw==,iv:JZRy6Q9l/d/1gPBtyS5x1H9W7HRoqxK5FdxFRg8/qIY=,tag:qvHCL0FeQXog7dzP+1giAw==,type:str]
sops:
  age:
    - recipient: age1uf6rlc8hlh4d9q5l5wy29tkg6xdftzcyufsy8zzj0c0w4atffemswtpdkl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNzFZdTBPRUVCczlNZkgx
        U2h2YVpkQm5Fc1l0ZTB1YWk2V1lLaFRyR1NzClJXTGVvTHo2Rng0Z2xxM0I4UUpn
        SGt6OUtnSnlQY2lNQldBaEpOSUZxL1EKLS0tIDdNbkVhdDh1d1ovbE45L2ZjQ202
        QXBadzdVYU56bHFPcmRMQkFUSkFFZkkK2RugiDIRoAbcncZlX/BJ8rozS6lVNvHa
        ywQ15leYp3VDWJCEdoV2EDwpFAtuss0IaI4DRLN2jByp/ZF4fMfo1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-18T18:11:14Z"
  mac: ENC[AES256_GCM,data:eHPrbYHHmqUriMmljx/eBuosgmvHJJeVHMCun7eCXSCPwypIcP+IK1KyjhM7anmBol//1+tkZ4Nwgv0kL5BhWYjL/mtd0QHenuERKgWPBf0C3XX2zVNOV7iJrfcFoGDgVp801qlbf4frVBgAKcjkFVHqKm8JsakAKIQJIxviJq0=,iv:JvRaDQFCYZ+ql6C62CG42asIZcf/kYQ6EEGclz9KpRE=,tag:3rmv4O9Kc1T+YmhkCvH6Jg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
