---
# yaml-language-server: $schema=https://schemas.vwn.app/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: checkmate
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: develop
  url: https://github.com/bluewave-labs/checkmate
