---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.10.3-standalone/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${VOLSYNC_CLAIM:-${APP}}"
spec:
  accessModes:
    - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${VOLSYNC_CLAIM:-${APP}}-bootstrap"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:-1Gi}"
  storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
