---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${VOLSYNC_CLAIM:-${APP}}"
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 * * * *"
  restic:
    accessModes:
      - "${VOLSYNC_SNAP_ACCESSMODES:-ReadWriteOnce}"
    cacheAccessModes:
      - "${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-65534}
      runAsGroup: ${APP_GID:-65534}
      fsGroup: ${APP_GID:-65534}
    pruneIntervalDays: 7
    repository: "${APP}-volsync-secret"
    retain:
      hourly: 24
      daily: 7
      weekly: 4
    storageClassName: "${VOLSYNC_STORAGECLASS_SOURCE:-longhorn-cache}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn-snapclass}"
