---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${VOLSYNC_CLAIM:-${APP}}"
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: "${APP}-volsync-secret"
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn-snapclass}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-8Gi}"
    cacheAccessModes: [ "${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}" ]
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
    accessModes: [ "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}" ]
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID:-65534}
      runAsGroup: ${VOLSYNC_GID:-65534}
      fsGroup: ${VOLSYNC_GID:-65534}
    retain:
      hourly: 24
      daily: 7
      weekly: 5
