---
# yaml-language-server: $schema=https://schemas.vwn.app/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app echo
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/tailnet
  wait: false
  prune: true
  interval: 1h
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/default/echo/app
  postBuild:
    substitute:
      APP: *app
      GATUS_NAME: Echo
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
