---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: privatebin
spec:
  defaultBackend:
    service:
      name: privatebin
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - privatebin
