---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 1h
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
      # Bump timeout to tolerate slow/loaded kubelets:
      - --kubelet-request-timeout=10s
      # Scrape a bit less aggressively to reduce noise/load:
      - --metric-resolution=30s
      # Optional: remove this unless you specifically need it
      # (defaults already use the kubelet secure port 10250)
      # - --kubelet-use-node-status-port
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
    # Optional but good hygiene so it never starves:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
