---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flux-github-app
  data:
    - secretKey: githubAppID
      remoteRef:
        key: GitHub App
        property: githubAppID
    - secretKey: githubAppInstallationID
      remoteRef:
        key: GitHub App
        property: githubAppInstallationID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: GitHub App
        property: githubAppPrivateKey
