# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vZd4dn0dgi1dE/oouv0wYy8eoSWlIOyCNvxQDDWat84=,iv:mmW3OH5al3mp0WAdrVeEkUljbpgpfsCSSz92Dei2hDE=,tag:QrGnTuHzuT8Mdok4a5uVKw==,type:str]
sops:
  age:
    - recipient: age1kk5hqm27rv9l4engrl8xvudqnzlsrs698z22lmy5409v0ha66pjq02rhuq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK3lxY3RoZkNtTW9nbGZZ
        bktHQTl2bzRpenNaaU8wUWJEZUU0WFVkcm5vCmhJRFBoZVJGaGNuMDM3TnVDVzFU
        YjFTQnpsT21sV3Z3Y0Q5K2ZmUUlIeUUKLS0tICtVVk9UUXFDVWVrL3B5Mmg0K29t
        eFNsajB0LzhlUG81TVpZdDJXQUFwSnMKKsiNmA+KIQcg+x86H0gXODWcFji+SQXY
        yaQ09YwxToTbBJb3AMIDjm+PAm7Rv049wE4g6BdQKBxR2ZfcQgoJ8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T13:35:56Z"
  mac: ENC[AES256_GCM,data:5Uks8obdaGx287+cmyrZmDM5ikP4olg1kr9m3X9QqgaptXxvPAoGCzJ7wdIvdwFzvFo9/CiY81ZaB/y+pLwWi43PGtuzbKQx/HzIcyiiIkes9ZyKvHI1tJ2BT6HHZQD/caHR8rfWnF4J+vJCfnm4z9LSQaohZbwQT9gfKIgC6ls=,iv:yexQdR6MN7QDzKwUP5O0I98sMbWr3V8rrhMd44k7GHk=,tag:Fs8EilX3Pe4ka0yCM8KA4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
