# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nMc8GfKJSiYipnhqzc6KApvKZeN0bqoJHYZwR8blvuE=,iv:gpwjd4eQNAGwDVUWVeIPbomI0/S0MkRNVaK86ymYDXE=,tag:NvnOv3cfUMcq36We/GiJnA==,type:str]
sops:
  age:
    - recipient: age1a0x95hacw74cgqsaqda2f837e6cpz6r4ey7fg5kvqmwm9htk5fgq2nvx6r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RllaNDI1ZklPbWhOeDh4
        TkdSeDB1THdiaGZVRWthQmtXUW9iaElIRmxnCnlJb0dkOGE1dHJKRVp4NUhvSyt4
        RlRjcVpaVUlFdzByZmxGTXN4QzMrSHMKLS0tIHpub2lRT2RrNnpRVUMwYWp6NEk1
        U3JWd1FIMVhQWHVYeVk3VTEzenRhMTgKjdwxDp5bIaIZWoCZbzbUyKbZdPaX5JeR
        Xwpr/p7aWRbJ/GajJ4r7nIIYS2hvB1mMSYIMvUJbsGqiloaBVPX/JA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-17T17:23:19Z"
  mac: ENC[AES256_GCM,data:1zVgYZgB64ZYP/aJ0NjU2/2hnYEhf1jm6sMYznzM670CHc7fdF1LkhSSxyFtlKNupiH2p2wn2glbo7rSImp5Ib5Iybb0yY9ywsKpg6jjRNvDHwxdpEQfQ2qJcqEdhr3fJg4aoxBwSFIxso3qDTvFTh1Wg8lE5r6kskvTF0V19bE=,iv:cWtdLpd8J1QajHdNIe4mj5+7P/js7TUNtbGMXRS30KI=,tag:unC1bzHYDZEH7EGdQtVbPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
