# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:7BI4vzGRD3+BMQS5W5QqzpgjXkifvkmsXnCajMf4/Hg=,iv:ZbiTPi0iPuwmxQzkPDjq7YjI23oCvp/Hy6yhlZKn3Xw=,tag:XorCVKvEhrLDMsgMi7t45g==,type:str]
sops:
  age:
    - recipient: age17dwj6gpcv9evtrhwa8e0xcast9j2z50qha5rwl7c9jldynxwkqgqmmkxf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aWgwRnN1c29TcUJHRmp2
        V0NHYW1uU1Awd1VsQy9ZSUJ6d3JlUmNKM1FzCnFGZFNOMjJjdlNaNlh6b3hTc3l6
        UmppNGEyeExxeFByMldudUZxdUsvQkEKLS0tIFYyQSt0Qml4MVJ5L3Z1T0FmUDRj
        b2dOVFNSZEg3VmhiQkE1cDREM0w1LzQKyS4+H1CsxJw+H1wK7mcO0juWRtUzDZm/
        wSRtzV81MMp5te3mXoKXgH58LGZhIFmCIvnH3VQXo2W2/jDSEcGfCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-12T20:38:20Z"
  mac: ENC[AES256_GCM,data:nEcjUL0lfHJ7Z+F1nB2xMkmi3VJV6u2hNND5UVBMlRTACEXYLX23jEmZZ7NKVTKzxRU4oG7JNFUG4Cwf3ZA6dlaSYskNIAG7pBuroBwuKW3HjNnDAKqHQJEj1EQv2YQ1PMMcBpJn+1m+idGm7o4o/++R6TDk0dplLrbaHYc2M3w=,iv:xsFJh3/HUC6vG5pmy+zTNAacTaOHsTlIkuS66ZPA1WI=,tag:V9El9G9Z2fC8gMDphEv+ag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
