---
# yaml-language-server: $schema=https://schemas.vwn.app/helm.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: &namespace security
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/public
    - ../../../../components/volsync
  wait: false
  prune: true
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  path: ./kubernetes/apps/security/authentik/app
  postBuild:
    substitute:
      APP: *app
      GATUS_NAME: Authentik
      GATUS_DOMAIN: auth.vanwetten.id
      VOLSYNC_UID: "1000"
      VOLSYNC_GID: "1000"
      VOLSYNC_CLAIM: authentik-config
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_CACHE_CAPACITY: 1Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
    - name: cloudnative-pg-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
