---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: &namespace security
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components: []
  wait: false
  prune: true
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  path: ./kubernetes/apps/security/authentik/app
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
      - name: cluster-secrets
        kind: Secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: cloudnative-pg-cluster
      namespace: database
    - name: redis
      namespace: database

