---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: checkmate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: checkmate-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        # Official chart expected format
        JWT_SECRET: "{{ .CM_JWT_SECRET }}"
        REFRESH_TOKEN_SECRET: "{{ .CM_REFRESH_TOKEN_SECRET }}"
        SYSTEM_EMAIL_ADDRESS: "{{ .SMTP_USERNAME }}"
        SYSTEM_EMAIL_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SYSTEM_EMAIL_HOST: "{{ .SMTP_SERVER }}"
        SYSTEM_EMAIL_PORT: "{{ .SMTP_PORT }}"
        PAGESPEED_API_KEY: "change_me"  # TODO: Add to 1Password if needed
        DB_CONNECTION_STRING: "mongodb://mongodb:27017/uptime_db"
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        DB_TYPE: "MongoDB"
        TOKEN_TTL: "3600"
        REFRESH_TOKEN_TTL: "86400"
        # MongoDB credentials for the chart's MongoDB deployment
        MONGODB_ROOT_USER: "{{ .CM_DB_USER }}"
        MONGODB_ROOT_PASSWORD: "{{ .CM_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: checkmate
      rewrite: [{regexp: {source: (.*), target: CM_$1}}]
    - extract:
        key: dragonfly
      rewrite: [{regexp: {source: (.*), target: DF_$1}}]
    - extract:
        key: smtp
      rewrite: [{regexp: {source: (.*), target: SMTP_$1}}]
