---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: checkmate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: checkmate-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        JWT_SECRET: "{{ .CM_JWT_SECRET }}"
        REFRESH_TOKEN_SECRET: "{{ .CM_REFRESH_TOKEN_SECRET }}"
        DB_CONNECTION_STRING: "mongodb://{{ .CM_DB_USER }}:{{ .CM_DB_PASSWORD }}@checkmate-mongodb:27017/checkmate"
        REDIS_CONNECTION_STRING: "redis://:{{ .DF_PASSWORD }}@${DRAGONFLY_SERVER}:6379"
        EMAIL_HOST: "{{ .SMTP_SERVER }}"
        EMAIL_PORT: "{{ .SMTP_PORT }}"
        EMAIL_USER: "{{ .SMTP_USERNAME }}"
        EMAIL_PASS: "{{ .SMTP_PASSWORD }}"
        # MongoDB credentials for Helm chart
        CM_DB_PASSWORD: "{{ .CM_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: checkmate
      rewrite: [{regexp: {source: (.*), target: CM_$1}}]
    - extract:
        key: dragonfly
      rewrite: [{regexp: {source: (.*), target: DF_$1}}]
    - extract:
        key: smtp
      rewrite: [{regexp: {source: (.*), target: SMTP_$1}}]
