---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: checkmate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: checkmate-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        # App Configuration
        JWT_SECRET: "{{ .CM_JWT_SECRET }}"
        TOKEN_TTL: "99d"
        DB_CONNECTION_STRING: "mongodb://checkmate:{{ .CM_MONGODB_PASSWORD }}@checkmate-mongodb:27017/uptime_db?replicaSet=rs0"
        REDIS_URL: "redis://:{{ .CM_REDIS_PASSWORD }}@checkmate-redis-master:6379"

        # MongoDB Configuration
        MONGODB_ROOT_PASSWORD: "{{ .CM_MONGODB_ROOT_PASSWORD }}"
        MONGODB_PASSWORD: "{{ .CM_MONGODB_PASSWORD }}"
        MONGODB_USERNAME: "checkmate"
        MONGODB_DATABASE: "uptime_db"

        # Redis Configuration
        REDIS_PASSWORD_SECRET: "{{ .CM_REDIS_PASSWORD }}"

        # Frontend Configuration (for combined FE/BE deployment)
        UPTIME_APP_API_BASE_URL: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}/api/v1"
        UPTIME_APP_CLIENT_HOST: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        CLIENT_HOST: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        ORIGIN: "${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"

        # Optional: Google PageSpeed API Key
        PAGESPEED_API_KEY: ""
  dataFrom:
    - extract:
        key: checkmate
      rewrite: [{regexp: {source: (.*), target: CM_$1}}]
