---
# yamllint disable rule:line-length
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: checkmate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: checkmate-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        DB_CONNECTION_STRING: "mongodb://checkmate-mongodb:27017/checkmate"
        REDIS_HOST: "checkmate-redis-master"
        REDIS_PORT: "6379"
  dataFrom:
    - extract:
        key: checkmate
