---
# GitRepository for QNimbus's improved Checkmate Helm charts with subcharts
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: checkmate
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: feat/2683-helm-subcharts
  url: https://github.com/QNimbus/Checkmate.git
  ignore: |
    # Ignore everything except the charts directory
    /*
    !/charts/
    /charts/*
    !/charts/helm/
    /charts/helm/*
    !/charts/helm/checkmate/
    # Exclude cached chart files that might contain old OCI URLs
    /charts/helm/checkmate/Chart.lock
    /charts/helm/checkmate/charts/
