---
# yamllint disable rule:line-length
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app checkmate
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      server:
        containers:
          app:
            image:
              repository: ghcr.io/bluewave-labs/checkmate-backend
              tag: v2.3
            envFrom:
              - secretRef:
                  name: checkmate-secret
      client:
        containers:
          app:
            image:
              repository: ghcr.io/bluewave-labs/checkmate-client
              tag: v2.3
            env:
              UPTIME_APP_API_BASE_URL: "https://${SERVER_DOMAIN}/api/v1"
              NGINX_ENVSUBST_TEMPLATE_DIR: "/etc/nginx/templates"
              NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx/conf.d"
              BACKEND_SERVICE: "checkmate-server.observability.svc.cluster.local"
    configmap:
      nginx-config:
        enabled: true
        data:
          default.conf.template: |
            server {
                listen       80;
                listen  [::]:80;
                server_name  localhost;

                #access_log  /var/log/nginx/host.access.log  main;

                location / {
                    root   /usr/share/nginx/html;
                    index  index.html index.htm;
                    try_files $uri $uri/ /index.html;
                }

                # redirect server error pages to the static page /50x.html
                #
                error_page   500 502 503 504  /50x.html;
                location = /50x.html {
                    root   /usr/share/nginx/html;
                }

                location /api/ {
                    proxy_pass http://${BACKEND_SERVICE}:52345;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
    persistence:
      www:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/share/nginx/html
      nginx-templates:
        enabled: true
        type: configMap
        name: checkmate-nginx-config
        globalMounts:
          - path: /etc/nginx/templates
            readOnly: true
      nginx-conf:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /etc/nginx/conf.d
    initContainers:
      init-permissions:
        controller: client
        container: app
        order: 1
        image: alpine:latest
        command:
          - sh
          - -c
          - >-
            chown -R 65534:65534 /usr/share/nginx/html &&
            mkdir -p /etc/nginx/conf.d &&
            chown -R 65534:65534 /etc/nginx/conf.d
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
    service:
      server:
        controller: server
        ports:
          http:
            port: 52345
      client:
        controller: client
        ports:
          http:
            port: 80
    route:
      server:
        hostnames:
          - "${SERVER_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: server
                port: 52345
      client:
        hostnames:
          - "${CLIENT_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: client
                port: 80
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
