---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app checkmate
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: charts/helm/checkmate
      version: ">=0.1.0"
      sourceRef:
        kind: GitRepository
        name: checkmate
        namespace: flux-system
  install:
    remediation:
      retries: 3
    disableWait: false
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
    disableWait: false
    timeout: 15m
  valuesFrom:
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.JWT_SECRET
      valuesKey: JWT_SECRET
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.REFRESH_TOKEN_SECRET
      valuesKey: REFRESH_TOKEN_SECRET
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.SYSTEM_EMAIL_ADDRESS
      valuesKey: SYSTEM_EMAIL_ADDRESS
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.SYSTEM_EMAIL_PASSWORD
      valuesKey: SYSTEM_EMAIL_PASSWORD
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.SYSTEM_EMAIL_HOST
      valuesKey: SYSTEM_EMAIL_HOST
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.SYSTEM_EMAIL_PORT
      valuesKey: SYSTEM_EMAIL_PORT
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.PAGESPEED_API_KEY
      valuesKey: PAGESPEED_API_KEY
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.DB_CONNECTION_STRING
      valuesKey: DB_CONNECTION_STRING
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.REDIS_HOST
      valuesKey: REDIS_HOST
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.REDIS_PORT
      valuesKey: REDIS_PORT
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.DB_TYPE
      valuesKey: DB_TYPE
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.TOKEN_TTL
      valuesKey: TOKEN_TTL
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.REFRESH_TOKEN_TTL
      valuesKey: REFRESH_TOKEN_TTL
  values:
    # Client (Frontend) Configuration
    client:
      enabled: true
      controllers:
        main:
          type: deployment
          annotations:
            reloader.stakater.com/auto: "true"
          containers:
            main:
              image:
                repository: ghcr.io/bluewave-labs/checkmate
                tag: frontend-dist
              resources:
                requests:
                  cpu: 15m
                  memory: 64M
                limits:
                  memory: 128M
      service:
        main:
          ports:
            http:
              port: 80
      ingress:
        main:
          enabled: false  # We'll use Gateway API instead

    # Server (Backend) Configuration
    server:
      enabled: true
      controllers:
        main:
          type: deployment
          annotations:
            reloader.stakater.com/auto: "true"
          containers:
            main:
              image:
                repository: ghcr.io/bluewave-labs/checkmate
                tag: backend-dist
              envFrom:
                - secretRef:
                    name: checkmate-secrets
              resources:
                requests:
                  cpu: 15m
                  memory: 128M
                limits:
                  memory: 256M
      service:
        main:
          ports:
            http:
              port: 52345
      ingress:
        main:
          enabled: false  # We'll use Gateway API instead

    # MongoDB Configuration (using Bitnami subchart)
    mongodb:
      enabled: true
      auth:
        enabled: false  # Start with no auth, can enable later
      persistence:
        size: 5Gi

    # Redis Configuration (using Bitnami subchart)
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false  # Start with no auth, can enable later
      master:
        persistence:
          size: 1Gi
