---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app checkmate
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: charts/helm/checkmate
      version: ">=0.1.0"
      sourceRef:
        kind: GitRepository
        name: checkmate-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
    disableWait: false
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
    disableWait: false
    timeout: 15m
  valuesFrom:
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.JWT_SECRET
      valuesKey: JWT_SECRET
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.REFRESH_TOKEN_SECRET
      valuesKey: REFRESH_TOKEN_SECRET
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.SYSTEM_EMAIL_ADDRESS
      valuesKey: SYSTEM_EMAIL_ADDRESS
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.SYSTEM_EMAIL_PASSWORD
      valuesKey: SYSTEM_EMAIL_PASSWORD
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.SYSTEM_EMAIL_HOST
      valuesKey: SYSTEM_EMAIL_HOST
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.SYSTEM_EMAIL_PORT
      valuesKey: SYSTEM_EMAIL_PORT
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.DB_CONNECTION_STRING
      valuesKey: DB_CONNECTION_STRING
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.REDIS_HOST
      valuesKey: REDIS_HOST
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets.REDIS_PORT
      valuesKey: REDIS_PORT
  values:
    client:
      image: ghcr.io/bluewave-labs/checkmate:frontend-dist
      port: 80
      ingress:
        enabled: false  # We'll use Gateway API instead

    server:
      image: ghcr.io/bluewave-labs/checkmate:backend-dist
      port: 52345
      protocol: "https"
      ingress:
        enabled: false  # We'll use Gateway API instead

    # Use MongoDB - official chart will create checkmate-mongodb service
    mongodb:
      image: mongo:7.0
      port: 27017

    # Provide secrets as values (the chart will use these to create its own secret)
    secrets:
      PAGESPEED_API_KEY: "change_me"  # TODO: Add to 1Password if needed
      DB_TYPE: "MongoDB"
      TOKEN_TTL: "3600"
      REFRESH_TOKEN_TTL: "86400"

    persistence:
      mongodbSize: 5Gi
