---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app checkmate
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: charts/helm/checkmate
      version: 2.1.x
      sourceRef:
        kind: GitRepository
        name: checkmate
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
    disableWait: false
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
    disableWait: false
    timeout: 15m
  valuesFrom:
    - kind: ConfigMap
      name: checkmate-helm-values
