---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmate-redis
spec:
  interval: 1h
  chart:
    spec:
      chart: redis
      version: 20.6.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: checkmate-redis
    
    auth:
      enabled: true
      existingSecret: checkmate-secret
      existingSecretPasswordKey: REDIS_PASSWORD_SECRET
      
    architecture: standalone
    
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 2Gi
        
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 512Mi
          
      podSecurityContext:
        enabled: true
        fsGroup: 1001
        
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsNonRoot: true
        
    # Disable replica for simple deployment
    replica:
      replicaCount: 0
      
    # Disable sentinel 
    sentinel:
      enabled: false
      
    metrics:
      enabled: false
