---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmate-mongodb
spec:
  interval: 1h
  chart:
    spec:
      chart: mongodb
      version: 16.5.40
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: checkmate-mongodb

    auth:
      enabled: true
      rootUser: root
      existingSecret: checkmate-secret
      secretKeys:
        rootPassword: MONGODB_ROOT_PASSWORD
        userPassword: MONGODB_PASSWORD
      usernames:
        - checkmate
      databases:
        - uptime_db

    architecture: standalone

    persistence:
      enabled: true
      storageClass: longhorn
      size: 8Gi

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi

    podSecurityContext:
      enabled: true
      fsGroup: 1001

    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true

    metrics:
      enabled: false

    # Disable unnecessary features for this deployment
    hidden:
      enabled: false
    arbiter:
      enabled: false
