---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app checkmate
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: charts/helm/checkmate
      version: ">=0.1.0"
      sourceRef:
        kind: GitRepository
        name: checkmate-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
    disableWait: false
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
    disableWait: false
    timeout: 15m
  valuesFrom:
    - kind: Secret
      name: checkmate-secret
      targetPath: secrets
  values:
    # Client (Frontend) Configuration
    client:
      enabled: true
      image:
        repository: ghcr.io/bluewave-labs/checkmate
        tag: frontend-dist
      service:
        main:
          ports:
            http:
              port: 80
      ingress:
        main:
          enabled: false  # We'll use Gateway API instead

    # Server (Backend) Configuration  
    server:
      enabled: true
      image:
        repository: ghcr.io/bluewave-labs/checkmate
        tag: backend-dist
      envFrom:
        - secretRef:
            name: checkmate-secrets
      service:
        main:
          ports:
            http:
              port: 52345
      ingress:
        main:
          enabled: false  # We'll use Gateway API instead

    # MongoDB Configuration (using Bitnami subchart)
    mongodb:
      enabled: true
      auth:
        enabled: false  # Start with no auth, can enable later
      persistence:
        size: 5Gi

    # Redis Configuration (using Bitnami subchart) 
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false  # Start with no auth, can enable later  
      master:
        persistence:
          size: 1Gi
