---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app checkmate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      checkmate:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/bluewave-labs/checkmate-backend-mono
              tag: "latest"
              pullPolicy: Always
            env:
              # Server Configuration
              PORT: &port 52345
              NODE_ENV: production
              
              # Database Configuration
              DB_CONNECTION_STRING:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: DB_CONNECTION_STRING
                    
              # Redis Configuration
              REDIS_URL:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: REDIS_URL
                    
              # Authentication Configuration
              JWT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: JWT_SECRET
              TOKEN_TTL:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: TOKEN_TTL
                    
              # Frontend Configuration (Combined FE/BE)
              UPTIME_APP_API_BASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: UPTIME_APP_API_BASE_URL
              UPTIME_APP_CLIENT_HOST:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: UPTIME_APP_CLIENT_HOST
              CLIENT_HOST:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: CLIENT_HOST
              ORIGIN:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: ORIGIN
                    
              # Optional: Google PageSpeed API
              PAGESPEED_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: PAGESPEED_API_KEY
                    optional: true
                    
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
                  
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
                
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
          
    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
        globalMounts:
          - path: /app/data
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
            subPath: logs
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
            
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
            
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Observability"
          gethomepage.dev/name: "${GATUS_NAME}"
          gethomepage.dev/icon: "checkmate"
          gethomepage.dev/description: "Website & API monitoring with uptime tracking"
        hostnames:
          - "${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
