---
# Converted from Bitnami MongoDB chart to bjw-s app-template for simplicity and to remove Bitnami repo dependency
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmate-mongodb
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
    disableWait: false
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
    disableWait: false
    timeout: 15m
  values:
    controllers:
      mongodb:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/library/mongo
              tag: 6.0
              pullPolicy: IfNotPresent
            # Explicit env (avoid envFrom to keep schema minimal)
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: CM_DB_USER
              - name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: checkmate-secret
                    key: CM_DB_PASSWORD
              - name: MONGO_INITDB_DATABASE
                value: checkmate
            resources:
              requests:
                cpu: 250m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - mongosh --eval 'db.adminCommand("ping")'
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - mongosh --eval 'db.adminCommand("ping")'
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6
        pod:
          securityContext:
            fsGroup: 999
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 8Gi
        storageClass: longhorn
        globalMounts:
          - path: /data/db
    service:
      mongodb:
        controller: mongodb
        ports:
          mongo:
            port: 27017
            protocol: TCP
