---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmate-mongodb
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: mongodb
      version: 16.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
    disableWait: false
    timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
    disableWait: false
    timeout: 15m
  values:
    architecture: standalone
    auth:
      enabled: true
      rootUser: root
      existingSecret: checkmate-secret
      rootPasswordKey: CM_DB_PASSWORD
      database: checkmate
      username: checkmate
      passwordKey: CM_DB_PASSWORD
    primary:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: "longhorn"
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    serviceAccount:
      create: true
    metrics:
      enabled: false
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
