---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./mongodb-deployment.yaml
  - ./redis-deployment.yaml
  - ./helmrelease.yaml
  - ./tailscale-ingress.yaml
