---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmate-mongodb
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: mongodb
      version: "16.5.40"  # Updated to latest available version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    architecture: standalone
    auth:
      enabled: false
    persistence:
      enabled: true
      size: 5Gi
