---
# yamllint disable rule:line-length
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmate-mongodb
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bitnami-mongodb
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    architecture: standalone
    auth:
      enabled: false
    persistence:
      enabled: true
      size: 5Gi
