---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkmate-nginx-config
  namespace: observability
  labels:
    app.kubernetes.io/name: checkmate
    app.kubernetes.io/instance: checkmate
    app.kubernetes.io/component: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;

        server_name localhost;
        server_tokens off;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Enable API proxy to backend server
        location /api/ {
            proxy_pass http://server:5000/api/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api-docs/ {
            proxy_pass http://server:5000/api-docs/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
