---
# yaml-language-server: $schema=https://schemas.vwn.app/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: *name
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        # To override the default UID/GID for Authentik, uncomment and set these values:
        # AUTHENTIK_UID: "1000" # Custom UID value
        # AUTHENTIK_GID: "1000" # Custom GID value


        # Database Init
        INIT_POSTGRES_HOST: "${DB_SERVER}"
        INIT_POSTGRES_DBNAME: "{{.POSTGRES_DB}}"
        INIT_POSTGRES_USER: "{{.POSTGRES_USER}}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Authentik
        AUTHENTIK_EMAIL__FROM: "{{ .EMAIL_FROM }}"
        AUTHENTIK_EMAIL__HOST: "{{ .EMAIL_HOST }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .EMAIL_PASSWORD }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .EMAIL_USERNAME }}"
        AUTHENTIK_POSTGRESQL__NAME: "{{ .POSTGRES_DB }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .POSTGRES_USER }}"
        AUTHENTIK_REDIS__HOST: "${DRAGONFLY_SERVER}"
        AUTHENTIK_REDIS__PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
        AUTHENTIK_SECRET_KEY: "{{ .SECRET_KEY }}"
        # GeoIP Updater
        GEOIPUPDATE_ACCOUNT_ID: "{{ .MAXMIND_ACCOUNT_ID }}"
        GEOIPUPDATE_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        GEOIPUPDATE_EDITION_IDS: "{{ .MAXMIND_EDITION_IDS }}"

  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: dragonfly
    - extract:
        key: cloudnative-pg
