---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: *name
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        # To override the default UID/GID for Authentik, uncomment and set these values:
        # AUTHENTIK_UID: "1000" # Custom UID value
        # AUTHENTIK_GID: "1000" # Custom GID value

        # Authentik Email configuration
        AUTHENTIK_EMAIL__FROM: "{{ .AK_EMAIL_FROM }}"
        AUTHENTIK_EMAIL__HOST: "{{ .AK_EMAIL_HOST }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .AK_EMAIL_PASSWORD }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .AK_EMAIL_USERNAME }}"
        # Redis configuration
        AUTHENTIK_REDIS__HOST: "${DRAGONFLY_SERVER}"
        AUTHENTIK_REDIS__PASSWORD: "{{ .DF_PASSWORD }}"
        # Authentik secret key
        AUTHENTIK_SECRET_KEY: "{{ .AK_SECRET_KEY }}"
        # GeoIP Updater
        GEOIPUPDATE_ACCOUNT_ID: "{{ .AK_MAXMIND_ACCOUNT_ID }}"
        GEOIPUPDATE_LICENSE_KEY: "{{ .AK_MAXMIND_LICENSE_KEY }}"
        GEOIPUPDATE_EDITION_IDS: "{{ .AK_MAXMIND_EDITION_IDS }}"

  dataFrom:
    - extract:
        key: authentik
      rewrite: [{regexp: {source: (.*), target: AK_$1}}]
    - extract:
        key: dragonfly
      rewrite: [{regexp: {source: (.*), target: DF_$1}}]
