---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2025.6.3
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: -1
    disableWait: false
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
    disableWait: false
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: authentik-helm-values
