---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./resources/postgres.yaml
  - ./resources/postgresuser.yaml
configMapGenerator:
  - name: authentik-helm-values
    files:
      - values.yaml=./helm/values.yaml
  - name: authentik-custom-assets
    files:
      - custom.css=./resources/assets/custom.css
  - name: authentik-custom-templates
    files:
      - password-reset.html=./resources/templates/password-reset.html
configurations:
  - ./helm/kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
