---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: authentik-custom-assets
    files:
      - custom.css=./resources/custom.css
    options:
      disableNameSuffixHash: true
resources:
  - ./helmrelease.yaml
