---
# This configuration tells Kustomize how to update service references in HTTPRoute
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - path: spec/rules/backendRefs/name
    kind: HTTPRoute
    version: v1
    group: gateway.networking.k8s.io
