---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-operator-helm-values
  namespace: tailscale
data:
  values.yaml: |
    operatorConfig:
      hostname: tailscale-operator
      defaultTags:
        - "tag:k8s-operator"

    proxyConfig:
      defaultTags: "tag:k8s"
