---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tailscale-operator
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: clientId
      remoteRef:
        key: tailscale
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: tailscale
        property: clientSecret
