---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app it-tools
  namespace: &namespace tools
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
  wait: false
  prune: true
  interval: 1h
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/tools/it-tools/app
  postBuild:
    substitute:
      APP: *app
      GATUS_NAME: "IT Tools"
      GATUS_SUBDOMAIN: tools
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
