---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
  namespace: &namespace tools
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: -1
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 15m
  values:
    postgresql:
      enabled: false

    redis:
      enabled: true

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: photo-library

    env:
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: secret-immich-db-user
            key: HOST
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: secret-immich-db-user
            key: LOGIN
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: secret-immich-db-user
            key: PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: secret-immich-db-user
            key: DATABASE_NAME
      LOG_LEVEL: info
      TZ: Europe/Amsterdam
      MACHINE_LEARNING_PRELOAD__CLIP: "ViT-H-14-378-quickgelu__dfn5b"
    envFrom:
      - secretRef:
          name: immich-secret

    image:
      # renovate: datasource=github-releases depName=immich-app/immich
      tag: v1.142.1

    server:
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 60
      resources:
        requests:
          cpu: 500m
          memory: 2048Mi
        limits:
          cpu: "4"
          memory: 4096Mi
      # Add startup probe to allow more time for Redis connection
      startupProbe:
        httpGet:
          path: /api/server-info/ping
          port: 2283
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 12  # 2 minutes total (12 * 10s)
        successThreshold: 1
      ingress:
        main:
          enabled: false

    machine-learning:
      resources:
        requests:
          cpu: 500m
          memory: 4096Mi
        limits:
          cpu: 3000m
          memory: 6144Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 60
      persistence:
        cache:
          type: pvc
          existingClaim: immich-machine-learning-cache
