---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app volsync
  namespace: &namespace volsync-system
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  wait: false
  prune: true
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  path: ./kubernetes/apps/volsync-system/volsync/app
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
      - name: cluster-secrets
        kind: Secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: snapshot-controller
      namespace: *namespace
    - name: longhorn
      namespace: longhorn-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
