---
# yaml-language-server: $schema=https://schemas.clustrs.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: &namespace flux-system
spec:
  interval: 1h
  url: https://immich-app.github.io/immich-charts
