---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app privatebin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      privatebin:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/privatebin/nginx-fpm-alpine
              tag: 2.0.0-alpine3.22@sha256:67684f8b14430b59c493c4cc52ec3ccc378878108589ee4a9e860e7072da278d
            env:
              TZ: "${TIMEZONE}"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            # No resource limits - BestEffort QoS - First pods to be killed on resource contention
            # resources:
            #   requests:
            #     cpu: 5m
            #     memory: 32Mi
            #   limits:
            #     memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        seccompProfile:
          type: RuntimeDefault
      shareProcessNamespace: true
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080
    persistence:
      data:
        existingClaim: "${VOLSYNC_CLAIM}"
        globalMounts:
          - path: /srv/data
            subPath: data
          - path: /srv/cfg
            subPath: configs
      config:
        type: secret
        name: privatebin-config
        defaultMode: 0444
        globalMounts:
          - path: /cfg/conf.php
            subPath: conf.php
            readOnly: true
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Tools"
          gethomepage.dev/name: "PrivateBin"
          gethomepage.dev/icon: "privatebin.png"
        hostnames:
          - "${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
        rules:
          - backendRefs:
              - identifier: app
                port: *port
