---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./tailscale-ingress.yaml
secretGenerator:
  - name: privatebin-config
    files:
      - config/conf.php
generatorOptions:
  disableNameSuffixHash: true
