---
# yaml-language-server: $schema=https://schemas.vwn.app/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: &namespace tools
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/interal
    - ../../../../components/volsync
  wait: false
  prune: true
  interval: 1h
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/tools/paperless/app
  postBuild:
    substitute:
      APP: *app
      GATUS_NAME: Paperless
      GATUS_SUBDOMAIN: archive
      VOLSYNC_CLAIM: paperless-config
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_CACHE_CAPACITY: 2Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: cloudnative-pg-cluster
      namespace: database
    - name: volsync
      namespace: volsync-system
