---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tailscale-operator
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_id: "{{ .TS_CLIENT_ID }}"
        client_secret: "{{ .TS_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: tailscale
      rewrite:
        - regexp:
            source: (.*)
            target: TS_$1
