---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-tailscale
  namespace: default
  annotations:
    tailscale.com/hostname: whoami
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: whoami
      port:
        name: http
  tls:
    - hosts:
        - whoami.buri-ray.ts.net
  rules:
    - host: whoami.buri-ray.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
