---
apiVersion: v1
kind: Service
metadata:
  name: whoami-tailscale
  namespace: default
  annotations:
    tailscale.com/hostname: whoami
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: whoami
    app.kubernetes.io/instance: whoami
