---
# yaml-language-server: $schema=https://schemas.vwn.app/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: "external.${DOMAIN_PROXII}"
      recordType: CNAME
      targets: ["75a96b44-0dfb-413a-9ed8-840137736a91.cfargotunnel.com"]
