# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Ffk0Yf330tN0/qOF4ZP6+I9WSVAy+F1EEepmWLmx94LLJtMw4YXuZjWbARtMZBbPpd4ECvHZui17Wtf5uFGsisvrsiaOarhZLT+URrHa5C1XBJDC9rRSlKjKN/CvwUfEX5PTAYwF/C2WqthOzGJg9evUG1SQ+uy6iCWa7sqWwV3KVpAZi1XtQOLrmqacfCby8Xa/2OlPzIGwZgcTmHUQY79cTxay4UKnlUn/vdLRlzj+dg5/,iv:FY6nzmomtmwRUBdlYfLgtOoLS11fyCwum8XGLwjuUHI=,tag:p7HR8QLbq03+smQ8UGp0tw==,type:str]
sops:
  age:
    - recipient: age17dwj6gpcv9evtrhwa8e0xcast9j2z50qha5rwl7c9jldynxwkqgqmmkxf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YnZzOXJpWHRYN1gzK1Rv
        UVltVFhVVzJXTzAzVUVadTdxR2kzR003M0RJClBVSTR6MHhtdVM1Z0dENEpnajVC
        Vzl0SkhLeHR1YklCeGdScC9UVkJDdzQKLS0tIE5kc3FPVGhHUG1nMVRnK3RqUXVE
        clpGZDFzRDJKVGdETENrWWVHdjFkczgKm3P39lvZK5zex4hfODQwjTZqAUPQwgpn
        HKGw30gczZBqYredVpBKb8E9OXxF/LcMuYfmVcpcBTd8t+cotKKlSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-12T20:38:19Z"
  mac: ENC[AES256_GCM,data:ZphFVl6/3FdolxLIVkaZ1QHRo6omn+BsL1VblWRQeBxZef8AtjKXEyedjo7kpC7yKYWTWAAlEwCcaDaflXk+tadJmNQkDuSygN/QRO7y+QDBewXwYsHgkUIl8gGulkTxP2WCKcg1Tatnkgk30uWMBaajAdmpWt95NDolXtf2abU=,iv:AaD+il3gYQP04SP5eT0pUPSa6G9zWEGoVlOGt0pPWgI=,tag:+q8OTKe+f+dZeW+20Uk9vg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
