# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:RboqqSXafPFq9nnbD++ioXFI7GCIsFcGqOiMKD1tGqBekgDk07YawOJC4b2xq3mmW3YWLk7A/CxlMR+kMKyv8pzPEl1vSeKyoYgwIVCuVYlk93/y2Ug/TGq2p2LLbidk1skgZs9k8YpLw01erHXqZzwHXgSnhdh6VPS1g4xUqyYjNQrIubDQmjEn45d5Fab8H2+UkqTb0ZXTKReSPZLUOKHFi10mNvVfXxq4X+8YOEFC6Ncc,iv:UITWLHELbT++DHkJmscRPEpw1jDJUqE3XMZbcVmGlXI=,tag:BoB7RZLFiEiwMAjnaPWWXQ==,type:str]
sops:
    age:
        - recipient: age14ytjrjdtj7azyqknt0cj854fqcyqlrrrkyck5kyc2ulkug70vswsj2w0k9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZmhmTis4S0EvS1JtZDd3
            eWd3VjFDaHg1ekR5RnRQTmZzbG9tRmpjSWxJCjJzczFLNGdmamVzQUYzOFNmUXdx
            QW9vS0xEL3BJSzdVRlpWdmNtTktmbHcKLS0tIGtnamJpeVRNTnZzV2VaWDRBRGNS
            UkpCaURLMGdTdUdmZExXYnhxNXI2c00KHRpJ50qSkuGXD7MTwmYJ33V6SF/98lMu
            FQZJH+TLX0OdqJiob4IcxCQIeOpmU/7qODG3vm5o23yYtNuunrea9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T18:07:35Z"
    mac: ENC[AES256_GCM,data:1KX3N1v4gFGwhMA3v/nKtwkzvc3I/rYymQTO2CE1SoEC2LiQ7daeg6QKZUHq+FxBgQqXZClkwTmIrxHvfmJFd9R9sngcjIJafUI1JoKcIL/mS1QxjE2WDAID4HhJTYXkFYD435rSRyh2+J6cdcoVU1Q7wG7RRp+NlqbycmA8M8Q=,iv:ip9QDY20KYvbmKD5fDfoA/eXZjKjeZKyxkhRgS3bdvw=,tag:zmLPsn6MhGeXObtj7/Ye/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
