# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Me5VV5UDo2SjVYf/di9jGWzCU2qaH/tl3QzSIKVFVdH/ksn1Or6Ee0zC9YRC78jokESzfKa+r7VtoZyZFxbJFDlo9FI+zxKJJ+PhilMwla26S0yY/yUT1pNCyqvOiu2Egm1eTvKBCjwT4alE7L35h3JKDWsv5rW/e+PgTXi5OeEQiV+jUlJq8bzfR7BWCmeRBBUmz05PCNEsJbM92BumwaYwurfEUI2kAcMVe3ejQrdFJd4h,iv:ZZp4w1gtRsYhqKZtKKZzChd6s5Zkx/yP6JpC5WHqvfE=,tag:O82Jq/gZ/dreB3zqZaIdFQ==,type:str]
sops:
  age:
    - recipient: age1kk5hqm27rv9l4engrl8xvudqnzlsrs698z22lmy5409v0ha66pjq02rhuq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMU0vT2hWQU01TFNudVp1
        OWswNUZ5blgrZVlqc0dxMldNV2ViZDloN0NJCkpuRldtSHBtd1dPdlZjcHVhZysv
        VGF5dHc2azA1VC8zVHQzSUZZTXFhVk0KLS0tIFlGbERpbTlZdnlFKy9VcEc1Z240
        SGhCaUVIVGw3NVNzREZqQWhDQm01VUkKITh2UPw/g+F6IDKwQ9tvShgQ/9l3AMdU
        7pdGWLcKsb7l3Fb2pR95RI8mjRVA0mghwgFZX9xWnaipb7rebvF5pQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T13:35:56Z"
  mac: ENC[AES256_GCM,data:HkHkS2DygOqX7/7YmXoPBnWWlRX+E7+RB64suV5lR6pwOLoRvW6MiWvHNwIwuavSYC/NZM1BXFssJsQVUGmqTh6bJfRh0/b5uWwFZgeoTeR8RS4hLrMlnuAUVkilZZ9VCLjgznVDW1HfybqkYX2mEkWKDyI4hYUgh+LDdMQ1z08=,iv:40A0auKUVsj2JHQiCe4I8w9u2ayWA0eQ1c3rT9vGEbo=,tag:ePxQkpp0jEG4j26TkhYIgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
