---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app microbin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      microbin:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/vaskozl/microbin-bin
              tag: 2.0.4@sha256:a12e470a11bb131e64ccad93bb4f449659459db149afe0cc0c3f210bb9742bdb
            env:
              MICROBIN_DATA_DIR: /var/lib/microbin
              MICROBIN_PORT: &port 8080
              MICROBIN_PUBLIC_PATH: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
              MICROBIN_SHORT_PATH: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
              MICROBIN_READONLY: "true"
              MICROBIN_HIDE_HEADER: "true"
              MICROBIN_HIDE_FOOTER: "true"
              MICROBIN_HIDE_LOGO: "true"
              MICROBIN_NO_LISTING: "true"
              MICROBIN_ENABLE_BURN_AFTER: "true"
              MICROBIN_WIDE: "true"
              MICROBIN_ETERNAL_PASTA: "true"
              MICROBIN_ENABLE_READONLY: "true"
              MICROBIN_HASH_IDS: "true"
            envFrom:
              - secretRef:
                  name: microbin-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            # No resource limits - BestEffort QoS - First pods to be killed on resource contention
            # resources:
            #   requests:
            #     cpu: 10m
            #     memory: 10Mi
            #   limits:
            #     memory: 80Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        seccompProfile:
          type: RuntimeDefault
      shareProcessNamespace: true
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /var/lib/microbin
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Tools"
          gethomepage.dev/name: "Microbin"
          gethomepage.dev/icon: "microbin.png"
        hostnames:
          - "${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
        rules:
          - backendRefs:
              - identifier: app
                port: *port
