---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pairdrop
  namespace: &namespace tools
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
  wait: false
  prune: true
  interval: 1h
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/tools/pairdrop/app
  postBuild:
    substitute:
      APP: *app
      GATUS_NAME: PairDrop
      GATUS_SUBDOMAIN: pairdrop
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
