---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-backup
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  dataFrom:
    - extract:
        key: cloudnative-pg
  target:
    name: cloudnative-pg-backup-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        POSTGRES_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_DB: "{{ .BACKUP_DB }}"
