---
# PostgreSQL Restore Job Template
# This is a reusable template for restoring PostgreSQL backups
#
# Instructions:
# 1. Copy this file and rename it (e.g., restore-job-YYYYMMDD.yaml)
# 2. Update the following fields:
#    - metadata.name: Change to unique job name
#    - BACKUP_FILE: Set the backup filename to restore from
#    - SINGLE_DATABASE: Set to a database name to restore only that database, or leave empty for full cluster restore
# 3. Apply with: kubectl apply -f restore-job-YYYYMMDD.yaml
# 4. Monitor with: kubectl logs -f job/JOB_NAME -n database
#
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-restore-YYYYMMDD  # UPDATE THIS
  namespace: database
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 4000
        runAsGroup: 4000
        runAsNonRoot: true
        fsGroup: 4000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: postgres-restore
        image: postgres:17
        command: ["/bin/bash"]
        args:
        - -c
        - |
          set -e

          # Configuration - UPDATE THESE VALUES
          BACKUP_FILE="daily/postgres-YYYYMMDD.sql.gz"  # UPDATE THIS: Path to backup file
          SINGLE_DATABASE=""                            # UPDATE THIS: Set to database name for single DB restore, empty for full restore

          # Set PostgreSQL password environment variable for authentication
          export PGPASSWORD="$POSTGRES_PASSWORD"

          echo "Starting PostgreSQL restore from backup: $BACKUP_FILE"
          echo "Full path: /mnt/backups/$BACKUP_FILE"

          # Verify backup file exists
          if [ ! -f "/mnt/backups/$BACKUP_FILE" ]; then
            echo "ERROR: Backup file not found: /mnt/backups/$BACKUP_FILE"
            echo "Available daily backups:"
            ls -la /mnt/backups/daily/
            exit 1
          fi

          # Wait for PostgreSQL to be ready
          until pg_isready -h postgres-v17-rw.database.svc.cluster.local -p 5432 -U $POSTGRES_USER; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

          echo "PostgreSQL is ready, starting restore..."
          echo "This will overwrite all data in the target database!"

          # Determine restore method based on SINGLE_DATABASE setting
          if [ -n "$SINGLE_DATABASE" ]; then
            echo "=== SINGLE DATABASE RESTORE MODE ==="
            echo "Restoring only database: $SINGLE_DATABASE"
            echo ""

            # Check if target database exists
            DB_EXISTS=$(psql -h postgres-v17-rw.database.svc.cluster.local -p 5432 -U $POSTGRES_USER -d postgres -t -c "SELECT 1 FROM pg_database WHERE datname='$SINGLE_DATABASE';" | xargs)

            if [ "$DB_EXISTS" != "1" ]; then
              echo "Target database '$SINGLE_DATABASE' does not exist. Creating it..."
              psql -h postgres-v17-rw.database.svc.cluster.local -p 5432 -U $POSTGRES_USER -d postgres -c "CREATE DATABASE \"$SINGLE_DATABASE\";"
            else
              echo "Target database '$SINGLE_DATABASE' exists, will be overwritten."
            fi

            echo "Extracting and filtering backup for database: $SINGLE_DATABASE"
            # Extract full backup and filter for specific database, then restore
            gunzip -c "/mnt/backups/$BACKUP_FILE" | \
            sed -n "/\\\\connect $SINGLE_DATABASE/,/\\\\connect [^$SINGLE_DATABASE]/p" | \
            sed '$d' | \
            psql -h postgres-v17-rw.database.svc.cluster.local -p 5432 -U $POSTGRES_USER -d "$SINGLE_DATABASE"

          else
            echo "=== FULL CLUSTER RESTORE MODE ==="
            echo "Restoring entire cluster from backup"
            echo ""

            # Extract and restore the full backup (pg_dumpall handles all databases)
            gunzip -c "/mnt/backups/$BACKUP_FILE" | psql -h postgres-v17-rw.database.svc.cluster.local -p 5432 -U $POSTGRES_USER -d postgres
          fi

          echo "Restore completed successfully!"
        envFrom:
        - secretRef:
            name: cloudnative-pg-backup-secret
        volumeMounts:
        - name: backups
          mountPath: /mnt/backups
          subPath: Database
      volumes:
      - name: backups
        nfs:
          server: truenas.lan.home.vwn.io
          path: /mnt/vault/cluster/cloudnative-pg
      activeDeadlineSeconds: 1800  # 30 minutes timeout
  backoffLimit: 3
