---
# yaml-language-server: $schema=https://schemas.vwn.app/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale-operator
  namespace: &namespace network
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  wait: true
  prune: true
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  path: ./kubernetes/apps/network/tailscale/operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
# yaml-language-server: $schema=https://schemas.vwn.app/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale-configs
  namespace: &namespace network
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  wait: true
  prune: true
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  path: ./kubernetes/apps/network/tailscale/configs
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: tailscale-operator
      namespace: network
