---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rook-ceph-dashboard-password # name expected by the rook operator
    template:
      engineVersion: v2
      data:
        password: "{{ .ROOK_CEPH_PASSWORD }}"
  dataFrom:
    - extract:
        key: rook-ceph
      rewrite:
        - regexp:
            source: ^password$
            target: ROOK_CEPH_PASSWORD
