---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unifi-dns-secret
    creationPolicy: Owner

  dataFrom:
  - extract:
      key: unifi
