# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
stringData:
    unifi-host: ENC[AES256_GCM,data:/LpFpPxATjDfuHwIJzje20epxA==,iv:TnrGpAw2dyNUndsFG+BcMheutBhaZhFOh7MCZUQGcTY=,tag:mW7lB1n1if0+vDp6Ll4Pkw==,type:str]
    unifi-api-key: ENC[AES256_GCM,data:Ggghp+wqXWXE7oDN6X6Ne7OaAE98t1Cy7NytY6IRtXU=,iv:5zvXMh/RsActYFdviLUGX6LiasDygoKr8lZctUM1Oy4=,tag:BswuvbzLXc2DKti2Ii8E4Q==,type:str]
sops:
    age:
        - recipient: age1a0x95hacw74cgqsaqda2f837e6cpz6r4ey7fg5kvqmwm9htk5fgq2nvx6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWE5LQzdtK2g5aDdNR0pG
            OFpDclVVbkdWeU8rSC9SWHMwZHdXRHhkZFZvClBRZEFPYm1DbkpMN1FiSFl4MUty
            SnNPZ2pWcUdFVXdVTUIzUnkvdUtvNVEKLS0tIC9aRUJIUjZndWlIbWtIQmYvQ1da
            bXZYMmNLTi9HdU52M3BOekRhZjFYcE0Kvo+IE38bEY/M/n3xG4JQxSlOhTbmfolM
            cods4EsvMIIDezphmpHDiIU/5ItAY6G1AFbT34rW3O3eowL7MvvVPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T18:16:01Z"
    mac: ENC[AES256_GCM,data:72vn8e8wIwWg4YFjOsA37YDjXnJaAdRwg1yWd5T1N7sGVYmacHiH73QY2S1mg0qJrO0v7OzKL2Wvzj6KiCXjawxUbfvzLdlkc0Uj71Ru0fPJqyirQi9JM6oKL7LHrEcvOFhWwYwNV3m2LatUFp8lyC+tX5TH7hiEPsLYb34N4sA=,iv:RqyAG6KkUTGCHUijl0U//UEIe38wjei9l09qeATIayQ=,tag:lr/0D4Y7oVNMHny3vIU/+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
