---
apiVersion: v1
kind: Service
metadata:
  name: &app truenas
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
