endpoints:
  - name: "${GATUS_NAME:=${APP}}"
    group: "4. Tailnet Applications"
    url: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}}.buri-ray.ts.net${GATUS_PATH:=/}"
    interval: 1m
    ui:
      hide-hostname: false
      hide-url: false
    client:
      dns-resolver: tcp://10.43.0.10:53
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
