---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace tools
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/common
    - ../../../../components/gatus/internal
    # Disabled VolSync to use direct SMB photo library
    # - ../../../../components/volsync
  wait: false
  prune: true
  interval: 1h
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/tools/immich/app
  postBuild:
    substitute:
      APP: *app
      GATUS_NAME: Immich
      # Removed VolSync substitutions - using direct SMB storage
      # VOLSYNC_CLAIM: immich-library
      # VOLSYNC_CAPACITY: 50Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    # Removed VolSync dependency - using direct SMB storage
    # - name: volsync
    #   namespace: volsync-system
