---
apiVersion: v1
kind: Namespace
metadata:
  name: not-used
  labels:
    # TODO: Enable Pod Security Standards for enhanced security across all namespaces
    # Uncomment the following lines to enforce restricted pod security policies:
    # Benefits:
    # - Prevents privileged containers and host access
    # - Enforces non-root user execution
    # - Requires read-only root filesystems where possible
    # - Drops all capabilities by default
    # - Provides centralized security policy management via common component
    #
    # Before enabling, verify all workloads are compatible with restricted standards:
    # pod-security.kubernetes.io/enforce: restricted
    # pod-security.kubernetes.io/audit: restricted
    # pod-security.kubernetes.io/warn: restricted
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
