# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:m/4/T8J/0eSp8vbICmFvd+AzuoRQWUZKojm49WZ750lgWnsskqmvOQ==,iv:q6ikD21WKraF1LxaEN5lizUlF+5Y41BaktVPS5Jp84w=,tag:ummby2vW8IDw+qIVLIJn1A==,type:str]
sops:
  age:
    - recipient: age1kk5hqm27rv9l4engrl8xvudqnzlsrs698z22lmy5409v0ha66pjq02rhuq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETTZ6TVIxelF6Y015VFo5
        NlZZbUpUNDlSVkFpSHpaWXFBUHlpT25NT21ZCkFSbVVmQW1mdnpsV1dxYnhvUXRI
        U3lBVy9ZdFBXekJUVjJ4SHdWWnNxRFkKLS0tIGpkc3BxODBteEJsUURPbklJNk9C
        LzhtWk5mWktpUjlUa3B3L1phbUtyMkEKD5lAzroWMOWPXXvd0aHtMlYVqAUpURks
        EoRWiHcjiDlJxtd07icwXUeF5seP48qoCn2hodtqJENbg+qRuZPf4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T13:35:56Z"
  mac: ENC[AES256_GCM,data:tyoBkXFEtW3SgU5qK4ImFOLvJ61gTXEQLbXPgIOcqFjd5QrjQuvqTBdsmsb7Q0Tml05pZJzw7iPQxnmhHrqzFjBETFbCKPKA3LHa8m9Ce4UGTQKRk8yypBFMh+B19/FZ1G0/E+VPx/PbIwDH7G7jqG9hGHXDCMd972TH/vqjGpc=,iv:HLnUky5xYHdqAWb1wRQCt5wy5tLvGRrHamAKHRRgnA0=,tag:W4VPgnTty7uhGPQs+iqMCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
