# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NyunRxhLlfJUwxgONc9g6oOt7Zs2evOQKVmcW43X5Nf7/PbQUvg0oQ==,iv:F2pIEbXXI2tVyXuL+FgNOw+uWxQtKCxEK8KlpqU2lHE=,tag:el7PwXUSl4tAnwSCBXp32Q==,type:str]
sops:
  age:
    - recipient: age1uf6rlc8hlh4d9q5l5wy29tkg6xdftzcyufsy8zzj0c0w4atffemswtpdkl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZWhFVXBnelZkZmlKK2t4
        TkppbTRsRUJWVkdrQ1hGWldETEMzblMybkJjCjM2dmp1aFZZNHdJM1dGMDRJNUhC
        VnVNblJ1OC9MNEtUZTJybVE2YjNZRFkKLS0tIFhlNk5PNUp3eUdlWWN6Z1k4b1dp
        MncwZ2J0UTB3ZDEvTWhPdURmUU44OW8KYTxSkfQmgG8L0W7vN4TjlDpL+PpyFNN2
        6/ed3nhZJn0gRPgW31dPrFtdoaC95xhFKhmwvD9OP/1phTXc1v7T+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-18T18:11:14Z"
  mac: ENC[AES256_GCM,data:jmKskOAsTqfDneEo6YyedXSmHwv34pfiytZeoL9zyFp25BkMh/WyB2qmWeCfh4pajkipyDh2Y6lQWesZi1MJM7ojBIjeDAn4kFI5+JMiKBRCosGLcGmhektyLdgntGZnLBUM6CQ1zPxEkAdkdTnkqTVYwh2t8BgJRcTdiyog1SY=,iv:mFWQtRCNs9BmMsxA6iZ80794Wr79E+gjcnymgKYnVWg=,tag:sXUDODVFiEhXnr4S/VkPgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
