---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8JMz/ZHz8B2ej6Am7QQCfXnG7QkplQkPbczZw5Gm/NkPsU7wamtXPg==,iv:weGvOEYwCmFyu3JqQ5GiYK1jpRvmHgOHzXwYiP3fACI=,tag:aLy4jYD/X6Ko2aI6qc6UIg==,type:str]
sops:
  age:
    - recipient: age14ytjrjdtj7azyqknt0cj854fqcyqlrrrkyck5kyc2ulkug70vswsj2w0k9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MlJ1Tlp5NlRmRDFCL25I
        RHB4RXJwaHRxSEpRclljeVp4ZmtTU3FGSkhzCkgzYVRxSDlCcm03dFg1UXBYMWdR
        RWJmR0hhTWpicnFtbUp0V0hNTy92L2MKLS0tIGZWQ05DRTBpWWdtUTJ1ck9MZHVZ
        dVp0bm1NczNlM3lkcEtnYndxOWxtN3MKbvOJgNm/VXrhSsagBUlca81r4hCgGGUS
        zSfLRIMR1hN4brIUX5UnqMAX+3zpLtEWr0Z36DBa9wLG7OCU0lRmYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-22T19:02:22Z"
  mac: ENC[AES256_GCM,data:1bZipwynK7oxWkB//NyCI9IjNsEyZ80xk8bG9l8NT5UEpxTDPHioiQfkToHdS+sKrYuq8tlJv3oGYIDRZTPkTfkBDluj6eVHYm4IfG+uJwsx8ZpTJSoYBEOGZ2USkPk1DCZCLYUupgdR3mqdkG4sQk3tnOa2C7invWPiBJTenng=,iv:JiLG4Lg3GnOkMCN5WN7PG7R2DjUHQ3NBrc6Cn2NXUzI=,tag:VY7+eg9EBxcRlyCsmufT5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
