# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZuvISKitoB1vW2L68K/phOwibBs6RP/rYXq8H1wzRBDQim3wIO/4Rg==,iv:rNo+rr7cE1rMciwEx9fPkpEqxo/lKVMzW2GKHBuugRg=,tag:44pYxWAkW0265tElpkGXUg==,type:str]
sops:
  age:
    - recipient: age17dwj6gpcv9evtrhwa8e0xcast9j2z50qha5rwl7c9jldynxwkqgqmmkxf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRFJCT1hwcGRqVFQ1M3N0
        NFI1Nko5c1lTSUd1V0xSUy9POS9uNndXL1RrCnRtVVd3dlQ0MmJJRXZzM1lZWEl1
        SVF3M0k2eWVoVG1PSFk4Umg5UDJjOVEKLS0tIFJucHVOeU44NFE0TFExUWNWbHoy
        YjR6eWVpYzUxVU9EY2RoZk9TTjJlRkEKkY/E1f3eGLOSmOaF9t5VXoS/6XjVoSUA
        s89EXtonZgBnJTQ4ToRhuKvN5ZwEGVrAgEkkPO3MGcXZCU3GPLhnLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-12T20:38:20Z"
  mac: ENC[AES256_GCM,data:2yNWY5kIlJDIDhq6BYrQJCsjAhVmKULzdhUPiuNy8sN1lren3ZjhcwETRbFaaI2+V20grOT5vBcJz49qICrqaeywigJNLSWcLE0tYvMHQfskBReW2vvpJPslFXgf8d9tpx4lUB3EwEQE6B8cEf0CybGXYFJSVtJEs41X8QBWKG0=,iv:ytGThBjR6dykfrxSA/UU1m5L8hNSfa4pARnrK0FnYA4=,tag:5lQuOaVCLliMHXKx2TQZWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
