---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/persistentvolume.json
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: tools-smb-photo-library
spec:
  capacity:
    storage: 2T  # Adjust based on your photo collection size
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - noperm
    - cache=strict  # Better performance for read-heavy workloads like photo serving
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: tools-smb-photo-library
    volumeAttributes:
      source: //${SMB_SERVER}/photos  # Adjust path as needed
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kube-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/persistentvolumeclaim.json
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photo-library
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T
  volumeName: tools-smb-photo-library
  storageClassName: smb
