---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.1.2
            env:
              BASE_URL: https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}
              ALLOW_SIGNUP: true
              API_DOCS: false
              TZ: ${TIMEZONE}
              WORKERS_PER_CORE: 1
              MAX_WORKERS: 1
              WEB_CONCURRENCY: 1
              DB_ENGINE: postgres
            envFrom:
              - secretRef:
                  name: secret-mealie-db-user
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      config:
        existingClaim: mealie-config
        globalMounts:
          - path: /app/data
    service:
      app:
        controller: app
        ports:
          http:
            port: &port 9000
    route:
      app:
        hostnames: ["${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
        rules:
          - backendRefs:
              - identifier: app
                port: *port
