# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.60.0.2:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.60.0.2"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-k8s-node-1"
    ipAddress: "10.60.0.201"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/583560d413df7502f15f3c274c36fc23ce1af48cef89e98b1e563fb49127606e
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:38:f7:2e"
        dhcp: false
        addresses:
          - "10.60.0.201/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.60.0.1"
        mtu: 1500
  - hostname: "talos-k8s-node-2"
    ipAddress: "10.60.0.202"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/583560d413df7502f15f3c274c36fc23ce1af48cef89e98b1e563fb49127606e
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:17:e5:8f"
        dhcp: false
        addresses:
          - "10.60.0.202/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.60.0.1"
        mtu: 1500
        vip:
          ip: "10.60.0.2"
  - hostname: "talos-k8s-node-3"
    ipAddress: "10.60.0.203"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/583560d413df7502f15f3c274c36fc23ce1af48cef89e98b1e563fb49127606e
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:9b:78:e8"
        dhcp: false
        addresses:
          - "10.60.0.203/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.60.0.1"
        mtu: 1500
        vip:
          ip: "10.60.0.2"
  - hostname: "talos-k8s-node-4"
    ipAddress: "10.60.0.204"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/583560d413df7502f15f3c274c36fc23ce1af48cef89e98b1e563fb49127606e
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:e6:54:fa"
        dhcp: false
        addresses:
          - "10.60.0.204/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.60.0.1"
        mtu: 1500
        vip:
          ip: "10.60.0.2"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

