---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app n8n
  namespace: &namespace tools
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
    - ../../../../components/volsync
  wait: false
  prune: true
  interval: 1h
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/tools/n8n/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: n8n-config
      VOLSYNC_CAPACITY: 5Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
