originRequest:
  originServerName: "gateway.${DOMAIN_IO}"
  noTLSVerify: true

ingress:
  - hostname: "*.${DOMAIN_APP}"
    service: https://envoy-external.network.svc.cluster.local
  - hostname: "${DOMAIN_APP}"
    service: https://envoy-external.network.svc.cluster.local
  - hostname: "*.${DOMAIN_CASA}"
    service: https://envoy-external.network.svc.cluster.local
  - hostname: "${DOMAIN_CASA}"
    service: https://envoy-external.network.svc.cluster.local
  - hostname: "*.${DOMAIN_APPS}"
    service: https://envoy-external.network.svc.cluster.local
  - hostname: "${DOMAIN_APPS}"
    service: https://envoy-external.network.svc.cluster.local
  - hostname: "*.${DOMAIN_IO}"
    service: https://envoy-external.network.svc.cluster.local
  - hostname: "${DOMAIN_IO}"
    service: https://envoy-external.network.svc.cluster.local
  - service: http_status:404
