---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local:8080
      vaults:
        Kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            namespace: external-secrets # Required if using ClusterSecretStore instead of SecretStore
            name: onepassword-connect-secrets
            key: token
