---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/cert-manager/charts/cert-manager
  ref:
    semver: ">=1.0.0"