---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: coredns
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/coredns/charts/coredns
  ref:
    semver: ">=1.30.0"