---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace flux-system
resources:
  - ./app-template.yaml
  - ./blackbox-exporter.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./gha-runner-scale-set-controller.yaml
  - ./gha-runner-scale-set.yaml
  - ./grafana.yaml
  - ./k8s-gateway.yaml
  - ./keda.yaml
  - ./kube-prometheus-stack.yaml
  - ./loki.yaml
  - ./openebs.yaml
  - ./reloader.yaml
  - ./snapshot-controller.yaml
  - ./spegel.yaml
  - ./tailscale-operator.yaml
  - ./volsync.yaml
