---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/stakater/charts/reloader
  ref:
    semver: ">=1.0.0"