---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: spegel
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
  ref:
    semver: ">=0.1.0"