---
# yaml-language-server: $schema=https://schemas.clustrs.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/home-operations/charts-mirror/tailscale-operator
  ref:
    semver: ">=1.0.0"
