---
originRequest:
  originServerName: "external.${DOMAIN_PROXII}"

ingress:
  - hostname: "${DOMAIN_PROXII}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${DOMAIN_PROXII}"
    service: *svc
  - hostname: "${DOMAIN_ID}"
    service: *svc
  - hostname: "*.${DOMAIN_ID}"
    service: *svc
  - hostname: "${DOMAIN_APP}"
    service: *svc
  - hostname: "*.${DOMAIN_APP}"
  - hostname: "${DOMAIN_CASA}"
    service: *svc
  - hostname: "*.${DOMAIN_CASA}"
    service: *svc
  - service: http_status:404
