---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgadmin-secret
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_DEFAULT_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_DEFAULT_PASSWORD }}"
        pgpass: |
          postgres-v17-rw.database.svc.cluster.local:5432:*:{{ .CNPG_SUPER_USER }}:{{ .CNPG_SUPER_PASS }}
        servers.json: |
          {
            "Servers": {
              "1": {
                "Name": "postgres-v17",
                "Group": "Shared",
                "Host": "postgres-v17-rw.database.svc.cluster.local",
                "Port": 5432,
                "MaintenanceDB": "postgres",
                "Username": "{{ .CNPG_SUPER_USER }}",
                "Shared": true,
                "SharedUsername": "{{ .CNPG_SUPER_USER }}",
                "ConnectionParameters": {
                  "sslmode": "prefer",
                  "connect_timeout": 10,
                  "passfile": "/.pgpass"
                }
              }
            }
          }
  dataFrom:
    - extract:
        key: pgadmin
      rewrite:
        - regexp:
            source: (.*)
            target: PGADMIN_$1
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: (.*)
            target: CNPG_$1
