---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: happydomain
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      happydomain:
        strategy: Recreate
        containers:
          app:
            image:
              repository: happydomain/happydomain
              tag: 0.4.1@sha256:e60ba2a081b2dd9218db7afdc0f3a86dfe27262839bee450c8ddb2896d22e5ef
            env:
              HAPPYDOMAIN_DEFAULT_NS: "https://1.1.1.1:443/dns-query"
              HAPPYDOMAIN_DISABLE_EMBEDDED_LOGIN: "1"
              HAPPYDOMAIN_DISABLE_REGISTRATION: "1"
              HAPPYDOMAIN_EXTERNALURL: "https://happydomain.${DOMAIN_APP}"
              HAPPYDOMAIN_LEVELDB_PATH: "/data/"
              HAPPYDOMAIN_MAIL_SMTP_PORT: "587"
              HAPPYDOMAIN_NO_AUTH: "1"
              HAPPYDOMAIN_STORAGE_ENGINE: "leveldb"
            envFrom:
              - secretRef:
                  name: happydomain-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8081
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config-file:
        type: configMap
        name: happydomain-config
        globalMounts:
          - path: /etc/happydomain.conf
            subPath: happydomain.conf
            readOnly: true
      data:
        existingClaim: happydomain-data
        globalMounts:
          - path: /data
    service:
      app:
        controller: happydomain
        ports:
          http:
            port: *port
    route:
      happydomain:
        hostnames: ["happydomain.${DOMAIN_APP}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
        rules:
          - backendRefs:
              - identifier: app
                port: *port
