---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app checkmate
  namespace: &namespace observability
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
  wait: false
  prune: true
  interval: 1h
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/observability/checkmate/app
  postBuild:
    substitute:
      APP: *app
      GATUS_NAME: Checkmate
      GATUS_DOMAIN: "checkmate.proxii.nl"
      SECRET_DOMAIN: "proxii.nl"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: dragonfly-cluster
      namespace: database
