---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-lab-runner
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-lab-runner-secret
    template:
      engineVersion: v2
      data:
        github_app_id: "{{ .ACTIONS_RUNNER_APP_ID }}"
        github_app_installation_id: "{{ .ACTIONS_RUNNER_INSTALLATION_ID }}"
        github_app_private_key: "{{ .ACTIONS_RUNNER_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: actions-runner
      rewrite:
        - regexp:
            source: (.*)
            target: ACTIONS_RUNNER_$1
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anthropic
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: anthropic-secret
    template:
      engineVersion: v2
      data:
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
  dataFrom:
    - extract:
        key: anthropic
      rewrite:
        - regexp:
            source: (.*)
            target: ANTHROPIC_$1
