---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external
components:
  - ../../components/common
resources:
  - ./kvm-pve1/ks.yaml
  - ./kvm-pve2/ks.yaml
  - ./kvm-pve4/ks.yaml
  - ./nas/ks.yaml
  - ./printer/ks.yaml
  - ./proxmox-ve/ks.yaml
