---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./databases.yaml
  - ./helmrelease.yaml
  - ./paperless-secret.sops.yaml
  # - ./volsync.yaml  # TODO: Enable when VolSync operator is installed
