# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:9hAqJ35xJgl/nkARxFOlN9ykb14FH+MhH0MvdDI/zA03hhg1mIwKJdbCIo5uYpL+2ITgVZ26IesXbYYnOv78DXAMmff8zAr4wCL8TkC3S7Tcw+tGV1UwVw==,iv:amXN1lz2k3EVr0pB6w1TGDLFH1igupcVYCuDsESZWp0=,tag:qbrPxAQ9HAvDYZqL97cVVw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:gMOMnyGTYVQ6WOKwQoto6WRQaQSCkbntx8t7kx3W0VGFS7RcZojDaQYpsCNAczzUYaQI1o55d/gdnGntpDwUfzM9RgFulqZY/S5YkrHUh9fYWn5GCa/Aww==,iv:st4IRbDcxqdZjTNSTaBolXoY64PI070UhRy3l89Df2g=,tag:ohwnxKveVgwdKYlK2HSdEw==,type:str]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:NzkRl0MjBhRAMYMFblXVztOoBf+xHbuCdBV2ltKavJkzRYbTwZ3OY+krnP3adQ==,iv:gEkTv7lWMDvQfn1DtuGwdqhyj4bBz0sxkqW85WwkwaM=,tag:Cp/Fi+SAVK5J0LOpCQoLPg==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:RU/vikY4ouQY,iv:DH3mE49Qs5iHV3a26CrflLYwMmPw84feNA/WVUmSH5A=,tag:G9+m3CL/Veb8TGMlh3FCdQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:6SkQDTOUcYGKiQcSAy6uGjGAydzcwwEJDOkrlW+4BYA5Frd5zt+m3ZcGD/IB+32uk0h1M3YAPLMxqF58tMS/KMxU2QN30llvTUz8l/gQHCPQDc4sQQZWog==,iv:OlRhdv1tk/4cs168TdqkQ1VAERpVtOcByuE8jMf4ZJE=,tag:OJyLippwcTBMwnf5hb9VaQ==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:bB50OlLwDEHcqW9JsRz5X5Nr4ebgH4hM9uCqEdRnv49dPTAaA0xtabgL6Nu9emgboRMlSNnR1YRsxmqIDh0u,iv:kcIg33gxWHf1AEWMVpPxJIrSuRi8UW1K/H3Jp4koRuw=,tag:o5x1QF0oDmNvNK9k5iZ4kQ==,type:str]
sops:
    age:
        - recipient: age1uf6rlc8hlh4d9q5l5wy29tkg6xdftzcyufsy8zzj0c0w4atffemswtpdkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNzFZdTBPRUVCczlNZkgx
            U2h2YVpkQm5Fc1l0ZTB1YWk2V1lLaFRyR1NzClJXTGVvTHo2Rng0Z2xxM0I4UUpn
            SGt6OUtnSnlQY2lNQldBaEpOSUZxL1EKLS0tIDdNbkVhdDh1d1ovbE45L2ZjQ202
            QXBadzdVYU56bHFPcmRMQkFUSkFFZkkK2RugiDIRoAbcncZlX/BJ8rozS6lVNvHa
            ywQ15leYp3VDWJCEdoV2EDwpFAtuss0IaI4DRLN2jByp/ZF4fMfo1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T10:05:26Z"
    mac: ENC[AES256_GCM,data:VFhQ9BaTZadEwfG9rapXSnqTrT69C9SBqngX3ElnW8r4KaTGYNEFl1ggxEIdUfA+McHKrxRvt27TJuZcOAPiylvmBVvA3kUlTwaObXc5tvSoxhsMLw86vlzXuXr5blI6B3Ijq61ujVYfmUSEyHWggHVKCWyqnUcK55qbeN6yUD0=,iv:/CzWCLg6ps30F83+Zq/542cHc8GzC7eAccIDzl/D8yM=,tag:f1NdT6txKWHqMftQ+vEmCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
