---
# Longhorn-delete (same as Longhorn, but with Delete reclaim policy)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-delete
  annotations:
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
---
# Longhorn-cache (Longhorn storage class with best-effort data locality and single replica)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-cache
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
# volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: best-effort
  replicaAutoBalance: best-effort
