---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  data:
    - secretKey: access-key-id
      remoteRef:
        key: longhorn
        property: r2-access-key-id
    - secretKey: access-key-secret
      remoteRef:
        key: longhorn
        property: r2-access-key-secret
    - secretKey: s3-client-endpoint
      remoteRef:
        key: longhorn
        property: s3-client-endpoint
  target:
    name: longhorn-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access-key-id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .access-key-secret }}"
        S3_ENDPOINT: "{{ .s3-client-endpoint | default \"\" }}"  # For S3-compatible services
