---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./node-configs/talos-k8s-node-1.yaml
  - ./node-configs/talos-k8s-node-2.yaml
  - ./node-configs/talos-k8s-node-3.yaml
  - ./node-configs/talos-k8s-node-4.yaml
  # - ./recurring-jobs.yaml
configMapGenerator:
  - name: longhorn-values
    files:
      - values.yaml=./helm/values.yaml
configurations:
  - ./helm/kustomizeconfig.yaml
