---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: longhorn-values
    files:
      - values.yaml=./helm/values.yaml
configurations:
  - ./helm/kustomizeconfig.yaml
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./node-configs/kube-node-01.yaml
  - ./node-configs/kube-node-02.yaml
  - ./node-configs/kube-node-03.yaml
  - ./node-configs/kube-node-04.yaml
  # - ./additional-storageclasses.yaml
  # - ./recurring-jobs.yaml
