---
# yaml-language-server: $schema=https://raw.githubusercontent.com/garethr/kubernetes-json-schema/refs/heads/master/v1.6.9-standalone-strict/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}-media"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/garethr/kubernetes-json-schema/refs/heads/master/v1.6.9-standalone-strict/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}-redis"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/garethr/kubernetes-json-schema/refs/heads/master/v1.6.9-standalone-strict/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}-postgresql"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
