# ---
# # yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.10.3-standalone/persistentvolumeclaim-v1.json
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: "${APP}-media"
# spec:
#   accessModes: ["ReadWriteOnce"]
#   resources:
#     requests:
#       storage: 500Mi
#   storageClassName: longhorn
# ---
# # yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.10.3-standalone/persistentvolumeclaim-v1.json
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: "${APP}-redis"
# spec:
#   accessModes: ["ReadWriteOnce"]
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: longhorn
# ---
# # yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.10.3-standalone/persistentvolumeclaim-v1.json
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: "${APP}-postgresql"
# spec:
#   accessModes: ["ReadWriteOnce"]
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: longhorn
