---
# yaml-language-server: $schema=https://schemas.vwn.app/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coder
spec:
  interval: 1h
  url: https://helm.coder.com/v2
