---
# yaml-language-server: $schema=https://schemas.clustrs.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ext-postgres-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://movetokube.github.io/postgres-operator/
