---
# yaml-language-server: $schema=https://schemas.vwn.app/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: goauthentik
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.goauthentik.io/
