---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  target:
    name: paperless-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        # Database Init
        INIT_POSTGRES_HOST: "${DB_SERVER}"
        INIT_POSTGRES_DBNAME: "{{.PL_POSTGRES_DB}}"
        INIT_POSTGRES_USER: "{{.PL_POSTGRES_USER}}"
        INIT_POSTGRES_PASS: "{{ .PL_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .DB_POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .DB_POSTGRES_SUPER_PASS }}"
        # App Configuration
        PAPERLESS_ADMIN_USER: "{{ .PL_ADMIN_USER }}"
        PAPERLESS_ADMIN_MAIL: "{{ .PL_ADMIN_MAIL }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PL_ADMIN_PASSWORD }}"
        PAPERLESS_API_KEY: "{{ .PL_API_KEY }}"
        PAPERLESS_DBNAME: "{{ .PL_POSTGRES_DB }}"
        PAPERLESS_DBPASS: "{{ .PL_POSTGRES_PASSWORD }}"
        PAPERLESS_DBUSER: "{{ .PL_POSTGRES_USER }}"
        PAPERLESS_LOGOUT_REDIRECT_URL: "{{ .PL_LOGOUT_URL }}"
        PAPERLESS_REDIS: redis://:{{ .DF_PASSWORD }}@${DRAGONFLY_SERVER}:6379/2
        PAPERLESS_SECRET_KEY: "{{ .PL_SECRET_KEY }}"
        PAPERLESS_FILENAME_FORMAT: "{{ .PL_FILENAME_FORMAT }}"
        PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: "{{ .PL_FILENAME_FORMAT_REMOVE_NONE }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
                "APPS": [
                  {
                      "client_id": "{{ .PL_OIDC_CLIENT_ID }}",
                      "name": "VanWetten ID",
                      "provider_id": "vanwetten-id",
                      "secret": "{{ .PL_OIDC_CLIENT_SECRET }}",
                      "settings": {
                        "server_url": "{{ .PL_OIDC_SERVER_URL }}"
                      }
                  }
                ],
                "OAUTH_PKCE_ENABLED": true
            }
          }
        PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: "{{ .PL_SOCIAL_ACCOUNT_SYNC_GROUPS }}"
  dataFrom:
    - extract:
        key: paperless
      rewrite: [{regexp: {source: (.*), target: PL_$1}}]
    - extract:
        key: dragonfly
      rewrite: [{regexp: {source: (.*), target: DF_$1}}]
    - extract:
        key: cloudnative-pg
      rewrite: [{regexp: {source: (.*), target: DB_$1}}]
