---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: &secret onepassword
  data:
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: paperless
        property: paperlessAdminUser
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: paperless
        property: paperlessAdminPassword
    - secretKey: PAPERLESS_API_KEY
      remoteRef:
        key: paperless
        property: paperlessAPIKey
    - secretKey: PAPERLESS_LOGOUT_URL
      remoteRef:
        key: paperless
        property: paperlessLogoutURL
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: paperless
        property: paperlessSecretKey
    - secretKey: PAPERLESS_SOCIALACCOUNT_PROVIDERS
      remoteRef:
        key: paperless
        property: paperlessSocialAccountProviders
    - secretKey: PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS
      remoteRef:
        key: paperless
        property: paperlessSocialAccountSyncGroups
  target:
    name: paperless-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_API_KEY: "{{ .PAPERLESS_API_KEY }}"
        PAPERLESS_LOGOUT_REDIRECT_URL: "{{ .PAPERLESS_LOGOUT_URL }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: "{{ .PAPERLESS_SOCIALACCOUNT_PROVIDERS }}"
        PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: "{{ .PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS }}"
