---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: tika
    - name: gotenberg
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.18.3@sha256:6dbe57d8198fa117158ba9e867e2d45280b65e9c37ea54c1df7b34c4085a564c
            env:
              # Database configuration from ext-postgres-operator generated secret
              PAPERLESS_DBHOST:
                valueFrom:
                  secretKeyRef:
                    name: secret-paperless-db-user
                    key: HOST
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: secret-paperless-db-user
                    key: LOGIN
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: secret-paperless-db-user
                    key: PASSWORD
              PAPERLESS_DBNAME:
                valueFrom:
                  secretKeyRef:
                    name: secret-paperless-db-user
                    key: DATABASE_NAME
              # OIDC integration
              PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
              PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
              PAPERLESS_DISABLE_REGULAR_LOGIN: "false"
              PAPERLESS_REDIRECT_LOGIN_TO_SSO: "false"
              # Configure application
              PAPERLESS_PORT: &port 8000
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_TIME_ZONE: "${TIMEZONE}"
              PAPERLESS_URL: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
              PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}},https://archive.${DOMAIN_APP},https://paperless.${DOMAIN_TS}"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "15"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGE: nld+eng
              PAPERLESS_OCR_LANGUAGES: nld
              # Configure Tika
              PAPERLESS_TIKA_ENABLED: true
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
              PAPERLESS_TIKA_ENDPOINT: http://tika:9998
              # s6 overlay fixes
              # Ref: https://github.com/just-containers/s6-overlay/issues/600
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"
              S6_READ_ONLY_ROOT: "1"
              S6_VERBOSITY: "2"
            envFrom:
              - secretRef:
                  name: paperless-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0  # No delay needed with startup probe
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10  # Small initial delay for container startup
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30     # Allow up to 5 minutes instead of 10
            resources:
              requests:
                cpu: 25m
                memory: 2Gi
              limits:
                memory: 6Gi
    persistence:
      config:
        existingClaim: paperless-config
        globalMounts:
          - path: /usr/src/paperless/data
      archive:
        existingClaim: smb-paperless-archive
        globalMounts:
          - path: /usr/src/paperless/consume
            subPath: consume
          - path: /usr/src/paperless/export
            subPath: export
          - path: /usr/src/paperless/media
            subPath: media
      backups:
        existingClaim: smb-backups
        globalMounts:
          - path: /mnt/backups
            subPath: apps/paperless
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /usr/src/paperless/data/log
            subPath: log
          # s6 overlay fixes
          # Ref: https://github.com/just-containers/s6-overlay/issues/600
          - path: /run
            subPath: run
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Files Management"
          gethomepage.dev/name: "Paperless"
          gethomepage.dev/icon: "sh-paperless-ngx-light"
          gethomepage.dev/widget.type: "paperlessngx"
          gethomepage.dev/widget.url: "https://${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_PAPERLESS_API_KEY}}` }}"
          gethomepage.dev/widget.fields: '["total", "inbox"]'
        hostnames:
          - "${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.${DOMAIN_APP}}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
        rules:
          - filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  add:
                    - name: Cache-Control
                      value: "no-cache, no-store, must-revalidate"
                    - name: Pragma
                      value: "no-cache"
                    - name: Expires
                      value: "0"
            backendRefs:
              - identifier: *app
                port: *port
    service:
      paperless:
        primary: true
        controller: *app
        ports:
          http:
            port: *port
