---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${APP}
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/reload: &secret paperless-secret
        containers:
          paperless:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.17.1
            dependsOn:
              - redis
            env:
              # OIDC integration
              PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
              PAPERLESS_DISABLE_REGULAR_LOGIN: "true"
              PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
              # Configure application
              PAPERLESS_FILENAME_FORMAT: "{ created }-{ correspondent }-{ title }"
              PAPERLESS_PORT: &port 8000
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_TIME_ZONE: "${TIMEZONE:-UTC}"
              PAPERLESS_URL: "https://archive.${DOMAIN_APP}"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "15"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGE: nld+eng
              PAPERLESS_OCR_LANGUAGES: nld
              # Configure Redis integration
              PAPERLESS_REDIS: redis://localhost:6379
              # s6 overlay fixes
              # Ref: https://github.com/just-containers/s6-overlay/issues/600
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"
              S6_READ_ONLY_ROOT: "1"
              S6_VERBOSITY: "2"
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 25m
                memory: 1Gi
              limits:
                memory: 3Gi
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 8.1.2
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - redis-cli ping
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
          #   args:
          #     - "--save 60 1"
          #     - "--loglevel warning"
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
        advancedMounts:
          paperless:
            paperless:
              - path: /usr/src/paperless/data/log
                subPath: log
              # s6 overlay fixes
              # Ref: https://github.com/just-containers/s6-overlay/issues/600
              - path: /run
                subPath: run
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        advancedMounts:
          paperless:
            paperless:
              - path: /usr/src/paperless/data
                subPath: paperless
            redis:
              - path: /data
                subPath: redis
      archive:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn
        advancedMounts:
          paperless:
            paperless:
              - path: /usr/src/paperless/consume
                subPath: consume
              - path: /usr/src/paperless/export
                subPath: export
              - path: /usr/src/paperless/media
                subPath: media
      backups:
        enabled: true
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: longhorn
        globalMounts:
          - path: /mnt/backups
            subPath: Apps/Paperless
    route:
      paperless:
        hostnames:
          - "archive.${DOMAIN_APP}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
    service:
      paperless:
        primary: true
        controller: *app
        ports:
          http:
            port: *port
