---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease-gotenberg.yaml
  - ./helmrelease-tika.yaml
  - ./helmrelease.yaml
  - ./tailscale-ingress.yaml
  - ./resources/postgres.yaml
  - ./resources/postgresuser.yaml
