---
# yaml-language-server: $schema=https://schemas.vwn.app/gateway.networking.k8s.io/ingress_v1.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
spec:
  defaultBackend:
    service:
      name: paperless
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - paperless
