---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
spec:
  defaultBackend:
    service:
      name: paperless
      port:
        number: 8000
  ingressClassName: tailscale
  tls:
    - hosts:
        - paperless
