---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
spec:
  defaultBackend:
    service:
      name: echo
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - echo
