---
apiVersion: v1
kind: Node
metadata:
  name: talos-k8s-node-2
  labels:
    node.longhorn.io/create-default-disk: 'config'
  annotations:
    node.longhorn.io/default-disks-config: |
      [
        {
          "path": "/var/mnt/longhorn-storage",
          "allowScheduling": true
        }
      ]
