apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qvw/ic7zCcpf,iv:LfB+sfxxTve1KaON8vY2PmJuaMR9drlo/gLknSpsjGo=,tag:j6FhLGeOBBTWRoDE/r08xA==,type:str]
    APP_DOMAIN: ENC[AES256_GCM,data:PoFOBRYqHA==,iv:k+0QHebWe+LCQYbVkfoEfaa0+7s6PlymAJYRMdxjo1E=,tag:r1W0L4PF/jHM3wtxCYM2uQ==,type:str]
sops:
    age:
        - recipient: age14ytjrjdtj7azyqknt0cj854fqcyqlrrrkyck5kyc2ulkug70vswsj2w0k9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUzZGem5ESVdjYVlqREYv
            UTBxL3NvMkNoZUhLaUZhMnczWDFmaW1YdTJnCnJScjQ0V2Y3bUdrelYxRklRN3J5
            ZGgrZnk0emVxaTlpTTBYaVo4NVJERTgKLS0tIGliQjNYbHRxbmN4QVZvUVY1QnB4
            TVFINUhyaE9EMmJrb2lvd05LMnYxQkkKudgd1NJgOugJn+wSgJ/F97zKW9UjQdU6
            RvHZWHGpiiQo4UmGRNT8kWaIIu5VDoOiqZ0uja7p07pptMjhmDATvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T06:07:12Z"
    mac: ENC[AES256_GCM,data:M/+7YQmteAJz6Cs8gmVx3XcOxSXITQW2kehi2x0WSLY6nlj1+sKs+clxWJDkIzCE8DwCi1pZNKGQ6jfXGzv4Bu1d1Jr6qJWXXaUqnXtXfeqqccux2+U2Aijf1+7lM+r/VJeBllau0YcGS+hMjS5ajg/BdfKD/iIiutC1N7/KQtQ=,iv:Tpdl/2KcUlT8PaTO7A46ZEsQINjJCMKqFCT8CL0O+Eo=,tag:Rq3NrJ36SupMt+6yAix/3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
