apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:1qTWEoIbHA==,iv:TrYcfDthyz3S+UEbTWV4nF8hG8Y1q4qnF8JWd59Q2mE=,tag:lQwHgSmohTKwp7WMUkAXbw==,type:str]
sops:
  age:
    - recipient: age17dwj6gpcv9evtrhwa8e0xcast9j2z50qha5rwl7c9jldynxwkqgqmmkxf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eGFIQ05HWTVvYkxuS0ZP
        K2VmcXgwajZJWWJsZlNrVWdLa1N5YWpXekg4Cm5vNGhqM0F0RDlPdE9QeE1Kd3d5
        QlF3d3pWOUpuVnF6TllRa1FlL1FYUjAKLS0tIE1OZlN3SVNhMTNpMzAvL21vRysz
        S3NwWXNVamt5VUUxNnVIZnlUb05NaHMK22N5ANR4n35THMAksGavc1fhOPhBOVrJ
        r9yHp2K7SSuku3aRUXx2ZEYHnVKR/9OTNHwnZ6cb0phNovpZ9Tw1ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-12T20:38:20Z"
  mac: ENC[AES256_GCM,data:uE/KZl67ETGap/Gfq/1kQAcQRlCtrqnUwfA6Q/KY0idJE2cWGePsqf3mlVo5Nr7vCTseJR/xryeUGM0qdVSBXCLPD497VUQfiOThtxcO1XPHfKwEkcye2gPtq9DvjDJqB5/MW+kgks2UlTAVQ4pltY0+1i01rgdCiGUHnpiQGxY=,iv:YWMwf8D1lX9oDIZGA/xI9t+LhjzgvJL/IsDMy0Z24f0=,tag:0FHuYISyg4Ht1iVdOmAFIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
