apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:pt4ocGq/iQ==,iv:LGsyL3J3IbuFCY3wFMkpUEWH29IeefxW+2DJjiVBPDc=,tag:5kNM1mYftNoS1Ywpd5VbUQ==,type:str]
sops:
  age:
    - recipient: age1kk5hqm27rv9l4engrl8xvudqnzlsrs698z22lmy5409v0ha66pjq02rhuq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTVJacEozSG9BNDJRNExs
        NFVNZ3FhbmZ5QXVvNUs1TmZDOUVwd0JOamlnCmdkOUJBMTBXa2NqU0J2U1k2czEy
        WjNaakgvRHplUkdsZUJMMHFkTDJpYnMKLS0tIDYxclZzQTdoK2Z4QWExRlBrWkFR
        VmRjUGg0SUtXTlJuMlBxbjU3M1RydTAKWlVBvcD/DQYgW9v8zSI3C90BdU3XLbEM
        PnocuzxV3Sho9glK/kweNUqGD2CHmT+dLZ4nmWFtmowv2rMQPvS8ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T13:35:56Z"
  mac: ENC[AES256_GCM,data:xvypV2v/E5zuhCWYFBnbpbKneKVh3ipHBvMNMxhl8i3hGG+wG+49hzTtdwQmd+Av3/tjZkI8uD261k3oNu8rFSlGch4MfDpqJszopVAXtvetEPx6T8Cs7d7zs7jRbNI+vu8NUhiqyNTDMV5LNtzoad1DPt06BxAJ/KDs9WPhxBM=,iv:U2dZ1iTHuda0/hnDcS/tPC0+fCgcAL5QL8krD9tfL7s=,tag:xpnXn5cy46/uycGIUQBZhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
