---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
  namespace: &namespace tools
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  wait: false
  prune: true
  interval: 1h
  timeout: 10m
  retryInterval: 2m
  path: ./kubernetes/apps/tools/pgadmin/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_UID: "5050"
      VOLSYNC_GID: "5050"
      VOLSYNC_CLAIM: pgadmin-config
      VOLSYNC_CAPACITY: 2Gi
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: cloudnative-pg-cluster
      namespace: database
    - name: volsync
      namespace: volsync-system
