---
# yaml-language-server: $schema=https://schemas.vwn.app/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: &app tailscale-operator
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.84.3
  url: oci://ghcr.io/home-operations/charts-mirror/tailscale-operator
---
# yaml-language-server: $schema=https://schemas.vwn.app/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tailscale-operator
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    oauthSecretVolume:
      secret:
        secretName: &secret tailscale-operator
    operatorConfig:
      hostname: *app
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret
