---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_PROXII/./-}-production"
spec:
  secretName: "${DOMAIN_PROXII/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_PROXII}"
  dnsNames: ["${DOMAIN_PROXII}", "*.${DOMAIN_PROXII}"]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_APP/./-}"
spec:
  secretName: "${DOMAIN_APP/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_APP}"
  dnsNames: ["${DOMAIN_APP}", "*.${DOMAIN_APP}"]
