---
# yaml-language-server: $schema=https://schemas.vwn.app/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_PROXII/./-}-production"
spec:
  secretName: "${DOMAIN_PROXII/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_PROXII}"
  dnsNames: ["${DOMAIN_PROXII}", "*.${DOMAIN_PROXII}"]
---
# yaml-language-server: $schema=https://schemas.vwn.app/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_ID/./-}"
spec:
  secretName: "${DOMAIN_ID/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_ID}"
  dnsNames: ["${DOMAIN_ID}", "*.${DOMAIN_ID}"]
---
# yaml-language-server: $schema=https://schemas.vwn.app/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_APP/./-}"
spec:
  secretName: "${DOMAIN_APP/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_APP}"
  dnsNames: ["${DOMAIN_APP}", "*.${DOMAIN_APP}"]
---
# yaml-language-server: $schema=https://schemas.vwn.app/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kvm-${DOMAIN_APP/./-}"
spec:
  secretName: "kvm-${DOMAIN_APP/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "kvm.${DOMAIN_APP}"
  dnsNames: ["kvm.${DOMAIN_APP}", "*.kvm.${DOMAIN_APP}"]
