---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${DOMAIN_PROXII}"
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: "10.60.0.5"
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "external.${DOMAIN_PROXII}"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.${DOMAIN_PROXII}"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.${DOMAIN_PROXII}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: ${DOMAIN_PROXII/./-}-production-tls
    - name: http-id
      protocol: HTTP
      port: 80
      hostname: "*.${DOMAIN_ID}"
      allowedRoutes:
        namespaces:
          from: All
    - name: https-id
      protocol: HTTPS
      port: 443
      hostname: "*.${DOMAIN_ID}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: ${DOMAIN_ID/./-}-tls
    - name: http-app
      protocol: HTTP
      port: 80
      hostname: "*.${DOMAIN_APP}"
      allowedRoutes:
        namespaces:
          from: All
    - name: https-app
      protocol: HTTPS
      port: 443
      hostname: "*.${DOMAIN_APP}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: ${DOMAIN_APP/./-}-tls
