---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  annotations:
    external-dns.alpha.kubernetes.io/target: "services.home.${DOMAIN_PROXII}"
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: "10.60.0.6"
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "services.home.${DOMAIN_PROXII}"
  listeners:
    - name: http-app
      protocol: HTTP
      port: 80
      hostname: "*.${DOMAIN_APP}"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https-app
      protocol: HTTPS
      port: 443
      hostname: "*.${DOMAIN_APP}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: ${DOMAIN_APP/./-}-tls
    - name: tls-app
      protocol: TLS
      port: 443
      hostname: "*.${DOMAIN_APP}"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
