---
# Kustomization that makes flux apply the checkmate manifests from the preview branch
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: checkmate-preview
  namespace: flux-system
spec:
  interval: 1m
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: checkmate-preview
    namespace: flux-system
  targetNamespace: tools
  postBuild:
    substitute:
      DOMAIN_APP: "${DOMAIN_APP}"
  dependsOn:
    - name: checkmate-preview
      namespace: flux-system
