---
# Preview resources for Checkmate: GitRepository + Kustomization
# Apply these to your cluster to have Flux reconcile the checkmate app from the feature branch.
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: checkmate-preview
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/QNimbus/home-ops.git
  ref:
    branch: test/checkmate-flux-preview
---
# Kustomization that applies only the checkmate app path from the preview branch
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: checkmate-preview-safe
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/apps/tools/checkmate
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: checkmate-preview
    namespace: flux-system
  targetNamespace: tools
  postBuild:
    substitute:
      DOMAIN_APP: "${DOMAIN_APP}"
  # dependsOn removed: GitRepository is the sourceRef; a Kustomization dependency named
  # 'checkmate-preview' did not exist which caused a reconcile error.
